apiVersion: v1
kind: Secret
metadata:
    name: unifi-reconcile
    namespace: unifi-reconcile
type: Opaque
stringData:
    #ENC[AES256_GCM,data:wQDSbZtek482ntctiRE7K5U8+xee7wJnIx4U6nwVAplJAEkFnGcd2rp4DgVwhGPsMiVMcNscuCPNRWXL4r8LEdXM/yPtxGwRZAM=,iv:NpvaPmWnbmLu52bDkfESCNI3VWJNjUGdgyWlSL5i4as=,tag:HsyqIiYhthhVSWbvidut/Q==,type:comment]
    #ENC[AES256_GCM,data:5KXvMO5hbKn6gYSl75bnouRdRZPNbaFxpM0jcCDOFk3MMzCThwFS8IykTQfQ6XG9H6GUhDBmUFUFcpl6efZDgavX/OMdmFeMD8rcEw==,iv:4S0k5p6K/kwl7TSn8nUM3vyqkUmvkzEROIJsiuXZgG4=,tag:l/6TswmZm+KnL0GWzPwxhw==,type:comment]
    #ENC[AES256_GCM,data:zgtGoeEfok5LTY+kLyUfbhX7RN6qYQE+w+64y5Ic3+8TZ6eAO25LmeoZk7V2YcDMqip4,iv:7dDaMgikBEMVhr1JsUisWAIOVkuDAGtgwTuWhsOgegE=,tag:1vv3fAvQ5O6LSxDRZUJlPg==,type:comment]
    UNIFI_API_KEY: ENC[AES256_GCM,data:ZoV8uXhOnUHOP1XBGGd/qtGwCSv2TU8oQxBX/ktx6H0=,iv:mOd8PKLLQbvG8wmnNx5VYsQ0lfA24jxYIDJjUPvo31E=,tag:TqKlFBktlkBPRsh1/gdfEg==,type:str]
    #ENC[AES256_GCM,data:FN0oMMXaB/3rZw6on/uw7suQrmUGri9msYBBcvsTVW1j/HO0o7tYALmHfvkmfpvU7IY+gd02,iv:qiBnXoF9cVSYd4YRbErFaYRswXWJZ0ntGWjjMDMBSHs=,tag:xsY/U+17WK70iN0HCwYoXQ==,type:comment]
    #ENC[AES256_GCM,data:w35SJ34YebeZd60mDp+cHsg61Omu4ip4OXNTR0TbBw9UGbg81lRcT8a5N3OmbTMHGjtCdYS/AfZOQzG8lv0dT55VqeBN40W1j51NMqW6EA4d8uHl+5/gCMzTe8M=,iv:fT95NDOvIBLxbCbDHl9NFlEi7jsrh0unJRoriKipA08=,tag:kf80k9sujM3f5xld2+JvFw==,type:comment]
    #ENC[AES256_GCM,data:V6Cr2Cn2p956Hk/wMtQ4LGHiwA1X4PiBG8ExRy+X3Yw/Xieppr/zwid1WECU,iv:BSqpTQGHjhgb2nlTqrh1PlVcdP5egjGJwGAQY9kjMdw=,tag:6yiEkfqqPuuCB6009czEmg==,type:comment]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:+gym7JCBe3cPWKxdSZhZsrYYZAfZvrA+4HpizMCg,iv:K6BsT4bQWq5nwS55iSBzeEYFrX/Ux0+7+52SfLtBUOQ=,tag:IdWNPtI6DSPPdYGEMvCX7w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRlhDckRMOEk3dnZ5RGRJ
            bkJ1KzNhY1RPcThBSzNHU3BxWXg3dnFuaTBJCk11WkVjY1dwWHNLTEwzZ3RzTmRW
            ckdUSmg2Y29QU0hzOGkvQVBCZVdqRzQKLS0tIFl2aUlXTEphaDJnb1N1eTRPaGlX
            aytXNndMQTdHSGdlTlE5ZHZiWkd0ZkUKcK60Dtvwm6hGkXvi+PYPFPukZnmxjelD
            oIBZLxeDFnibvQsr3Wx+h4k8dbnvYQxa4xlGKx1ZPK7nAsjOel6obA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:LAZqykF89+hNHl6Drhti8ZVCZ6hyL3nAHEhUdEwmLHjAX98DiUKnq6WR9BFQ1n3/MX8HKJ4G+LI5t2LAqRvgywZMNfWRcCiq3gyZQTY317zp11fqLGWpWKunOkEhqda/vkLUSKXPK3b+BS3gG/n8NnMzoiHnzCBJb0ztcXVXxd0=,iv:LuzaWAr0tdYBfu490Ap9pxhZwa6awAhLQf/y+TBJx6g=,tag:McV/DCVN2E8ZgES1xRK4tw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
