apiVersion: v1
kind: Secret
metadata:
    name: unifi-reconcile
    namespace: unifi-reconcile
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9GFPQL4ltrpGtoe6WnPRzppg9WddeCI5SnHCtTrGqClV6ke06Jl/9kGr7yasF/4xX3nCg9g+Cl0GdEDlJIuXOhCMndAwvI+ZI9Y=,iv:fIsSUnfb3FA6uGS1SvDLpEf3eKRCGR2uAfhMINVkHeM=,tag:gXm06fAs6iBMPj1LkYSkTQ==,type:comment]
    #ENC[AES256_GCM,data:mMZEU/8Mfm2KUTvEAHvOx+bQom7ZEET9n5IRqFMkpkrjeyeIvwL+iEIYMPAIZ6BKHEKnK4LlShnJPFfq6xsPxK2ZNhPiHrQip+r9gA==,iv:vC8ZwqwUJ3N0qHsfWYhhwnCcZCFh95iTGjt0NNj/Msg=,tag:GWDkFjXoEsOH5E4tOGI66g==,type:comment]
    #ENC[AES256_GCM,data:SZ1Mt3pzc9cpjdHlE17qI3tWa6yOWNFro2DvDNHy5VMEC8ZSGOtZfgn3VpSQR9DlKCJV,iv:iktfaf57s5hmRIdzgp8vGXYEytdvajBy271iyT0roG8=,tag:dMHHTGwpvRw8leTwp4+pFg==,type:comment]
    UNIFI_API_KEY: ENC[AES256_GCM,data:K7S+vNdE9EQU5eak/JM0zANKgLEblo8mgITBO8V9AQw=,iv:n+zGYpy5ikQuQsWioS7cV5ucSdqmjTiDp6XkJKo/Ykw=,tag:g90MEXAa/6R6mvhj4SxLfg==,type:str]
    #ENC[AES256_GCM,data:9jtMynCC0dDWj4ARpFhxEFjBz/pqtRQevduHYJeON1/k9aqFCyal57QpBa3MfRzZeQn5+xYV,iv:4BM7HaAM1NJnvIHKauD0e9MIdQ2xFBh/roEEUqffSnY=,tag:uCg7XHraLxCc6/kkFyGNXA==,type:comment]
    #ENC[AES256_GCM,data:Uhuc9M/+Kyt60AWuA7jaDEnjFp8pRjTwCz86q/zsD72grlxN6qOsrHMA4gKvRRbRhXBxoW3zmS4gHOU6e9tk7g+oCCOAN3wbBz4CJLkMvyLJ+kz1uAxMzOjQg54=,iv:a+nPAvP+ZB93AEu9g93roUubNez77e8ltvnyYB1gNwE=,tag:MgM7kku0f9Fy3BLqyJ4Naw==,type:comment]
    #ENC[AES256_GCM,data:RO/fgjBLCyaGPoZaMkfzXlS8TguiPv3mi+dqM9OozpbS1njVuPtvwIqQOdcK,iv:+D+u6MMLAQ0Tf5GQtG1s3LUa7iLpDzxdwxTAnUb0iwk=,tag:Gg6KNzNNZ1KiTlxq0PV2Bw==,type:comment]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Nv2ZiMj/gfgPC3dXV9H5docYG3wYRgBn9wqrJk1I,iv:s+12dNPR0KrA0sVuz0icEsRYRbmPsFZb2QzW1YzTa/o=,tag:mApt3of4nkUuepOO+5EoWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaEFvcnk3c3FGeFdQemU1
            L1dDa0VvWWN4ekplNFRPTFVhV0pld0dOalg4Cjd5bXZnWnk5WWxSbWg2TTRSM2ZJ
            UUR4b0hXZGIxOVZ1ZXJDcTM0NHREbUUKLS0tIGhBbEVscThIUG45TGZES3hFQlp1
            eGQ2R2tUSFNpS0lLelVKM24xaWNYS2sKmVourEAOZBzl4rGIYGLceBljc0OfDNHL
            6BP2GN/wP2W/JpxviovEolF13b832tz0JDKlJUhaNcTwKJxWs4HkMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-26T19:20:01Z"
    mac: ENC[AES256_GCM,data:C52WoEkOp6bzTiOOSbANRiqJXlUNYOEp4adR4P8ssLjP7hrJ4/FSdgP0YLk6hukfpCg7aBoaZRF7ex0+Nzgy1ch3xwimyy9Nu3r6QAtCZnbsIlHqDXpLSvAA2riixc5VsstDJ28NVCaaLZOTna4WEGcMVoeBMRemZV4TD6kWVcA=,iv:QY2jIDXJBcQwskjofKpUD8lnYMgrV1sKN6eayCRFGhc=,tag:MHoyCsbQKfiIQSRoYoTWEg==,type:str]
    version: 3.13.1
