apiVersion: v1
kind: Secret
metadata:
    name: unifi-reconcile
    namespace: unifi-reconcile
type: Opaque
stringData:
    #ENC[AES256_GCM,data:YCNswR3haieToxqKsNsSj+569+91pEm/C0ZsT8s4uel95mSXt6Z3MWCGNyyugwzWzX7S9m7a4BUif6uyjEDra7PqPWusZKw0/IY=,iv:+hftYvIXctE6E7pgN26622QApSdIPAa9tDspC4IjnzU=,tag:ZBAE+w8C35XKfYibK5Tdpw==,type:comment]
    #ENC[AES256_GCM,data:UY3YkqADq59kdt6kLrlHNzDTrU9VcCRlX0CZPaCENXvLt5+l5ur1XVuMXT1HKEDpPhLswbJwKQAbzxo/lLEJi9yGpNP4RqHeSoFgXA==,iv:ME6Yps94w2WghT+A97oMrYY7QmRpl5d/3MHeSCtH69s=,tag:M9bWV7slVGVbdW20uB2o8Q==,type:comment]
    #ENC[AES256_GCM,data:Ytc+OVJyRAOp5uLi9nenTdWGOdQf/GJZdCLriC++iyzLDOVpMdv5HivKdjf85giMX0Ux,iv:Ce05CgH64I6tLQlsofdUyStTFHmy2KYWQzkc8HCq3Es=,tag:DZ0D3x79lEbm7yophKQfFA==,type:comment]
    UNIFI_API_KEY: ENC[AES256_GCM,data:YbIRYzAU2bPYkAzxprlsJM7uYgD2iRF7zb4gOYECp/8=,iv:N3BD34AQtYveik6hLGdEevnp4VfIoXv/jmZq1zP2LGE=,tag:sjN0WpvLHJy+rEJm6hBFUA==,type:str]
    #ENC[AES256_GCM,data:yd9n22xUIbuQdpAWVSt4SZfP3D17sUbYyKDYr1sGon3FDPxRQfxy08rI5Sr/xS0wG+O/DFlp,iv:YiX/0Ufilj3GSCTp6yNsFqzeYR1pYaA5jJsWojTOYSw=,tag:T5Or0H5WoJ8XbdmylpXyzg==,type:comment]
    #ENC[AES256_GCM,data:l2k9L3oRTU78i2nnyULKZz+gxbWm9h26zH+a9CRYRw7eClXsEDVb/F+SCLEt8imZWwUq11XaOO9d6/Eeo8G8knk2h/0FtQEvp8yR+lGnzkHln0w1cCX3NUrRSmI=,iv:quGVJiZsfQ19N2Ajl5PNyFOBMIm56+ttgv8Z6tFx+Xw=,tag:jfRMW4X+xdWSp5AkLHfVtw==,type:comment]
    #ENC[AES256_GCM,data:K2miPI66eFj/bWeVH/LvjTxrz5Dj2BKMrMu1regLOGuGVaoapRhFqDG5D7mx,iv:J8LTxA+VaQ3ULs9ORfkKNtYZNVsMGQfQh/siDNAuN6c=,tag:fUuOdDE0pZij2nF04JPj9Q==,type:comment]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:i9Xi+fhSz+t9nG/lE4AZkBCPpOLimy3Dty5m+PQI,iv:9ltbMbHYuQN6anWpaCVX8ie9raFIQeWcWA9vc6aNMkE=,tag:oa7wGVhhxkGelOQHtYi31w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbW5RNFZiSkxPVHZRallm
            QnRYcnk5VGFkR3pqcnYwTjh1Q1BRUkYzN2xJCmRPdVVRV0pVTzRFb1RJc0g5OGIr
            VFJSL1N3NVUwYkVzK3g0NncyZWZMVGMKLS0tIDFnMlExUDlXR1NRNkFUMlBmc2RE
            ZUpDaUtZUU0wcDJwR09tVW9ldWRSNVEKPn8+gPCcYQ00cEAWTYaPJkviKt5k9T37
            ZDcXC1PPDw3xu7YC0Y+o9gWEB346JsEP5cSEtp36Qj4MAwFFAtC1TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:KhwZ1fjZG59t7ECmVfT28UAu7EhMO8FJ0Z15euFBpwpf5buv2dHGKB7DCZGM/swFsw/L9b00Cl5NQRLPWcJABoGmkiv26TzGFWmit26jKI54sfyYCGmQxOg8h0R76LhXgRQxfsG6nYhMkhMv4yXtdAJIiDhdEAYAyBO4V+qDNJk=,iv:uPboH1J+yxADcbNd7JnfGQEesMBnrFE+8pDrQ1j0twg=,tag:60GL6QhlmJUSeNYq6H7H9w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
