---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: tools
spec:
  releaseName: it-tools
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: it-tools
      version: 9.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 10207
            protocol: http

    ingress:
      main:
        enabled: true
        hosts:
          - host: tools.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: false
            ingressClassName: internal
          traefik:
            enabled: true
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: wethecommon-prod-cert
          homepage:
            enabled: true
            name: IT Tools
            description: Developer Utilities
            group: Tools
            widget:
              enabled: false

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi
