---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-fstrim
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/node-fstrim/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
