apiVersion: v1
kind: Secret
metadata:
    name: udm-ssh-secret
    namespace: alert-remediation
type: Opaque
stringData:
    udm-ssh-private-key: ENC[AES256_GCM,data:HjT59V23b9i/xBXRitRWvRlAjWssbuEVryig7B+r1knSqOg3aW1WyfVBSGP+7NheIJxxVwuwcU7yGgbgcgiszNnODnNHP5xZQvvnSE5lBxqr+SAQd2j0y9vSldWIOJXGmufdhxsq7N8+c0/0k1ZbrWIixfJJ9lymjhpdC7vrRQhDKEFDCiDye1ycH2TZB17ebWsUEzHwO2D8J1TyDpRD9UCNJDySUkvgWPkerNHMNk2qV6SKJ+Nu0ithJYV0WyC0X1iWC9rkXmwegXlXP+0IAwE7h0Q3547bki3H+TIC90TSpGk7Pm79kmfHkuG2mx8uYY/NkdvKfEIhsIl/djD5tfr8APoOZzNQ/jmCuNO6oHbpxGs2D2UNqBa0l30j1aKv/lkS+xVlZuEOsvqBj7wPDy0wsD5EKcad0EjeuDh0zHuORoJ6q699sSACpniVdH8kf/BUGAsZF8DKvqR8hYmynj7XcQbeTRGBs3yiLJ5dNGT7QepaTfUu+INfmgtZlDpjBqxTlg1v7qZAuZ5R9KTSEOMmcgr3MLMV3xMi,iv:LTiPSbd8XN0XCA2sn0TgDAmtKJbkJiwyJ/I7yLpA+nk=,tag:BAvdmj5zmgRVK56JuTvY2Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0djF0cS9jNEFTbFMxQWdp
            RE1UUGZ5ei8vL284dFhJRUE3a251ekhmWmtjCi81TDRxR2RyaVVaNXdPTjZLTU5I
            cnlCZ3ZsWFY3cmlsQkI4dTNBNTFmeHcKLS0tIDFOS29ERDArOGlkajJmRFIyNDZB
            dmNiVVJidVZqSkw5anFhVXdtcWlScTgKmJi6hcEwTB8VI+l1+OMthY7M5p+IH2T4
            sE2E58BPR9LxyNOOG2TVZwYU1E0ZDlrUZ7Pq9w1iQOH8DgyvHxtppg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:mAEQ+y8JVaFbAgLDaqz3rg/KtAAFq79u1qHqt43vIQ3nEpGFQEMg3Y846gphz2oCARFGwHvfqo2Ryoy1kk8qweVLMlKoKhs46GowHAY0q7bwywE3+pcDiIopyBAu6bOipCrM9tKDkzC1rsa/YwwGLALjwWYKna8fJ8dIw20p9u0=,iv:1p9HSN+RpiyK5bvleogGl+VUpm843fWkIeAKMGsfx1U=,tag:+i7UuhAtmvMf7OJPXP8VBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
