apiVersion: v1
kind: Secret
metadata:
    name: udm-ssh-secret
    namespace: alert-remediation
type: Opaque
stringData:
    udm-ssh-private-key: ENC[AES256_GCM,data:4yoOKnhn73r8FC3qTre6v4GE4lVehVpRr6tWb4TGn6dEN7J/VpePmxoSBKOh56tRQbXERRtHOh7j7xLhwnlORHXqpFtCoDbEdhMCU7dX+2ZDZP34vUJ1Aj9B0xQ2sbMdTLvgcL+JCVcUVH4CbmWLL70WHrQvURAng4/M5PFHkdk4eK0AbNNO+NQPSDW0TK/gCwXtcocdHZv3NCGjQMEZmEArXUwbthjDgJQ7G10CnvovrdZJp5Qi7YAqId80gMFE0GDm/5lnR9Zx8vjjJ8pbTqsnHJ7/fABl0BwsGWDtNzAHP9NIr5L7M1BP9ivu8oJNoVC6coAa75iVWVR3LK7Q2KPp5XBYSqX4GM4PzL55SFrhWFUvkCIopjI5cyxBijSQ8ItfD7gpPJDATJbsITcTN5NwhixzTy3ASLhBuHYqkvo2TD5YEB5ShIOirHemEbGdF57WPzhfmUYFkLpCmjQ7rfK4V+qpAOXbZ/xKOYmnEhhEFaWkwjdlzOENynCIjzl2+jfj754WRb8tD5bc5SkquTnTCtt1GLy/yLpE,iv:YCHG7/MNppGIsNqMZQ9ffSwufheP8p9oOE9f3Fnr8T8=,tag:qrw64XqO1PqBTZLaoCLBug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWnUzTGpEQWxIYTlpTTZ4
            YUJYNU5YUTBJVmpQZllJWkI1K3lMaERwYjBNClBYdkZza1Z5SWJGdGZvZk1KcUlp
            YnZoNjNURFJKb2dtRmZzc2xqN2wyN0EKLS0tIEpFRW9lTzUycm15WmRpOFhBR1Q3
            NGdDL0RkUjlnZnpyd2FaL2laRk1tYmcKARPXgAqx6a7H0TcY/DYYihdxCYCwyNiM
            tbANS6vrhbTrurvEHrfwwvgl1YrPCF6IyTzVXc+NAG4GUPl6E8yPFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:QQkF6qm2UzsC+AK3VGhoNV2SNIQ7xuF5Es7he9IzzSNP/rbkmuAk7dxPgTqIXAZPrzbBl/RiRBperal6S0othwLG5ClRp3CT19XkVYVTvNJhrLUxW2i9OrSENlAAr55XLd3HBmJsFhOu7swWiMw0zWaKgQQP3NQeBYxjZ1fTy9c=,iv:yJfMT7GC+aqOXxuSsAXQYdL8TPM8uNvXErk9yRwWlBc=,tag:pgGNJVq7VxFfRqgF3i3tJg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
