---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: tools
spec:
  releaseName: stirling-pdf
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: stirling-pdf
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    credentials:
      s3:
        type: s3
        url: ${S3URL}
        bucket: "${S3PREFIX}-stirling-pdf"
        accessKey: ${S3ID}
        secretKey: ${S3KEY}
        encrKey: ${S3KEY}

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 10266
            protocol: http

    ingress:
      main:
        enabled: true
        hosts:
          - host: pdf.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: false
            ingressClassName: internal
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: secure-chain
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: wethecommon-prod-cert
          homepage:
            enabled: true
            name: Stirling PDF
            description: PDF Toolkit
            group: Tools
            widget:
              enabled: false

    persistence:
      configs:
        enabled: true
        size: 1Gi
        volsync:
          - name: configs
            type: restic
            credentials: s3
            dest:
              enabled: false
              cacheCapacity: 2Gi
            src:
              enabled: true
              cacheCapacity: 2Gi
      custom-files:
        enabled: true
        size: 1Gi
      logs:
        enabled: true
        size: 1Gi
      tessdata:
        enabled: true
        size: 1Gi

    securityContext:
      container:
        readOnlyRootFilesystem: false

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 1Gi
