apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: ddns-cloudflare
type: Opaque
stringData:
    CF_TOKEN: ENC[AES256_GCM,data:ZhPamJD5B44xv5PyPhEZa3iz6ECwYhY3CWNei6FA8kweA2gbV7sBPg==,iv:IdHwirLtLbJVyFcGd3KxCyLxim8pRjPrkDcybZY95lA=,tag:g96oI7Fa8ivXTP81+mShLg==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:ZopqdyKmaLYnlw+2x7RAyvE/6f0s3MXbRcDDJb18j2U=,iv:hdiW1Jll4zl0JDRngB46lLNy9x4ofduBKCCqHuZmuLE=,tag:61joA8/NXEsl7l8CoS5TPA==,type:str]
    RECORD_ID: ENC[AES256_GCM,data:Z7vDBp1eFBBD3pSU1Nnu6XlCZ7bYoGN/3CMlSfBK0X4=,iv:e4KdpRITAygl0hFeVvZKSJievztxWEqs1wX2EGxBdxk=,tag:a8XUH7r9n8zrEzmpTarhPA==,type:str]
    RECORD_NAME: ENC[AES256_GCM,data:CMz3eREz+Fk7koky1rUE9W/iiw==,iv:XZogt0a4iPDWNm5709aYZYUOSCdEnQdKzpMDat1im2A=,tag:0HK8oJfKcFftZ6TRMSZ+0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa3BsYkJYOURKL1E5YUhC
            SEpkTTdnMkREQmM3azJxYnNja2RYZU96SUU0ClBoWDIzcFg0S2F4M2JaeGp3b01n
            bmxTMzVCZ3hZc2xvYkc0UnNKUGZqY28KLS0tIHo0bHR4RWZ3Ym1mMnJOd3ZLcHB5
            TzcyU2FzNlZ3SlQ3ck4rSmNkOXM0SVkKfGs5xF5TC73N5efSLHgJd20sJys3l042
            oXX++/FYFx2XgP5olQ3THRqdzRLSkZCOjCc/ts7oYPmMFa/biHJp6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:RO6Xlz4r1MBMDqOh7fXCU7borAej8N8zM3Vy78v0D/goQPNZ5pE827IFxYNW60Lm/LTvm6r6qXgPlKO66MbzYx/dQybuLfsEmI9YhK8pO2k2Yy8wbV+RtB5WJXrfZNsjiHSSIaw0B139ckaViASttS/iV2FjR03V3ozd4K54KPY=,iv:m6N0T/uYgLeLKLk/ZwRgc0yhbchNdrlFk2i2Xpa3g3U=,tag:Sd/vGvkeZYbkzlnPf6NIxg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
