apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: ddns-cloudflare
type: Opaque
stringData:
    CF_TOKEN: ENC[AES256_GCM,data:zRph00RKN/XfmnSzmdRLfM++5qot9Jvwe+m07mv9xIHoiO5JolUwTQ==,iv:/B/ye6yfXCInObxMKRnhPROWzMzm9n1FjH7qj0RycxE=,tag:ja8ec9GudyjIYgPoSxda1A==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:SNCf/w36QiZD0F8YVf/ZuV3Kzbh5o70G8ONkrrQuf/I=,iv:+fUbQxGJ/mzxayDtCU1N7j4ZuPgUVKWogvi6Pjl/I9E=,tag:gEbLWdks4t4fsnwNlaF7ZA==,type:str]
    RECORD_ID: ENC[AES256_GCM,data:BGdnnVZNA/QJzHJcXjaYtK/mZG+WatUbpWf6xWQcQ1w=,iv:pREAnlo3FR0Pmn9Ckr5QBdgR0eS233FJ96sw1oPJVvU=,tag:Upcg+XTEtiY+XJa2OfYJJg==,type:str]
    RECORD_NAME: ENC[AES256_GCM,data:5z0/6uKHXJxJRHTCnOYsAn35VA==,iv:Ql+Q5ejGDlJeX76vOM8QWiY57bcIyIaE2Qi6tSZgWeA=,tag:EZ2qS8GpuKRYSiaWW+4UPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNzg3dVhwY2J6blVvRkJn
            OHpLekFtNTUrNk83bDFWcTY4N002SXFpZzBBCk9UK1lpRFlMLzhyN0gwU0ZLaGZw
            QUdVMTIySGswajRmMXpYdDFvVWRMWVEKLS0tIDFiMG9DeXFmdElGZjNPM2ZBVkRU
            NDdsK21jZVdUSzBwTE9vbHdza1pqNVUKbYgOMBc+WmIZpfOcIEyPCK6+YokQIfMT
            xnJBk8lBQUnH3srrrzMFyuezV6MooZsSNC+vhRG9vSO2m/eG0BjGEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:p1vTKXc6rNZFjCgVLTZ3aSglUXZdJlM+KjK8cIMalY4sPpENEMoC01XI6k4wxjKDP8goyCo//ixBuRjxzZzYPVCNT63Lygy6U/7JIBT8PjwDI47eQdJHQejKnCclBn8s4aneCIL1EMLjVoiOn35xx37m8WoWT8a+64O0PjGNnFI=,iv:OK1IuABM+8m9lcqSODDhqWSGVUU2TQYELbWAaHj6ILs=,tag:jZ4cYG2BwyZhTcUxEISjDQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
