apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: ddns-cloudflare
type: Opaque
stringData:
    CF_TOKEN: ENC[AES256_GCM,data:g1ikf7PG9EkceRd/LGyQi+6NU0Y4IvkUlJH7x5F4LrAfh4dCJHmYsA==,iv:eOZkRBASWTKVoHysfe2+2pkyZe5fiJZGSVDHVjMHWwg=,tag:w7FWOzXAFGkw5eCaD0EbOQ==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:6o1HaeGi2KbN9Wq0wRxj5Y08NBNr7KNPghvwU7ObJDI=,iv:HD/uCKBixyz7xUW3CvinYUXIqZZV0ghbXxYcSKOkNHU=,tag:Ubfl5/iVl6wsK9UW03ymEA==,type:str]
    RECORD_ID: ENC[AES256_GCM,data:b/Mo27+iy//scwpJIdJQ3iYqZzWbu1f2/nkJ2CngzR8=,iv:7lNo+nG+a27qSP1BnMMGdwFYqwUstS+dDcy3W6qBdAM=,tag:HJaML3U+Ye8o/5wKYo9Xow==,type:str]
    RECORD_NAME: ENC[AES256_GCM,data:PdWFWPoZXk9d2cbvX78mjlJQ8w==,iv:ZV7r91JzK1r5oAWW+4PIVznKbuLEvcfltZ9u2jp9SYo=,tag:oa7pp3Sg16xJEp+5SPEuyw==,type:str]
sops:
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eFlNVjRYQ05QUGU0M3RF
            UjdaQVlVc3V1U1Axa0lrS2g5T1FjRml4UlVFCjFyM3V2MlNBbmZTWnMrOE9qK1NF
            dXJYc0NNRkhtQ1hkUmRwOFdXN1czRzQKLS0tIHVLdDhmVXlBVEFINjdnK2ZHYVU5
            aWdzTmUxU1JXOElqYlh1UWdNR1dxNncKEgMgxzKDFu9HWQrDAVf5QJ5OfNlpq3kN
            PC453QjDHFCQ/gaEgh721m7DhDD5AdrN5cfGetaNRtWIsnJzZgtW6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T01:51:12Z"
    mac: ENC[AES256_GCM,data:YxlPBJhQoEoyzpbL6rWh7yaf/9wp+WDgGIE5RE0ybISFr4pdNQS8VaXJ/gba5AM1tPOWPVZYjF485BdEEHwd0U6ooVmTxUOzFqYqRwiuMKktsoTiciohS9g0c411WNZjfksLkAoLNTxIjhqFMNuTjMxdDpxgnGqqiTjav5uDbYs=,iv:sGU9Kmk9vsTEU60CEnef//SMnls2O9evh5ttfjVrAFk=,tag:VzCWMWXVc+s4XezNxNKmaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
