apiVersion: v1
kind: Secret
metadata:
    name: mcpo-secrets
    namespace: mcpo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3wss2tJAa28OiTLGqx5LsOHbBSa2Nn5dgeAbMQw6eA==,iv:mDwmTm3dZUpFLKAGqDE82Ov+ZEAkV4tKL4aM32nSxCs=,tag:jaizUjmDAOfg1NTby21X9w==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:MBsplamccKzkTSXoYl5Hjev+krAnOr4oFv6tfpZ86jx9+Q4h/qJ50A==,iv:SmFWU+6nnkZqezNylwComCjRe35cMqnQUV0atBGDYcI=,tag:vOTmW6IpeI2nZD9inmMZxw==,type:str]
    TRIPARR_DISCORD_TOKEN: ENC[AES256_GCM,data:w9Ibt6bqyzupDVxMGykqXx43u0gkdmRNg88uQSj5+jyC4gz1hWrBI7INNP7aQaosrBtUZ2LygyA7zWvxS8QGnPEnVTxVV16/,iv:mqHfumnXNX/tHFMhtcwj9QEKLBJNNO1a7LstBZx82UE=,tag:N5WSUE4IFj4xgDFu28TjTw==,type:str]
    #ENC[AES256_GCM,data:As5AnWW3WFul+LMi/TtyORuFcU6EoqA=,iv:l7H9ZLCHwqryPv0VOgjly5YWx8+KiDfU69Fxea9+RRI=,tag:o6yRWrPEmkFyCY2ca1kcIA==,type:comment]
    GRAFANA_API_TOKEN: ENC[AES256_GCM,data:db8QKTHrJI7zVbvTv1CojtrIfU10ecvbZY+PURM2L2vUZqq3dXw71xS5Lcms7Q==,iv:SlJFTiRPPJ5+5RrfIDXeEhz6mspQbmxzbliq0s4xu0o=,tag:DzorMJwUaBLb8HkdFawhKQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:/wp4x0ZTUy7F06I5/h6jdtHp8WUHwlePmPYv+a5vQbvxWmmhjDKXMZOCct4+xXuJUoY7W936Y1Fb2fztTkfd0Kt8,iv:0sbFlg1NaoWd2zJcfuNDJTuIYu6swv9dwSW9SuQQjqU=,tag:8SKeJxJyafMIUbYYrrcllA==,type:str]
    #ENC[AES256_GCM,data:QKqwGqreRyzh0kQAWKG+KGkbtlyeeDGXWZ5S,iv:QA8q7wI0gqbeEzFnsqa6SVBv2nMGwm+L1udxMByHKuY=,tag:YH+O+Dcgx76atofW8tEEWg==,type:comment]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:PLFVckTZ00xGtJo=,iv:cN61Hhf0pOjvX1Rh+48wOePDIQZTghojkxPvzrTf630=,tag:+72OPJzs4Siqp8ng11dOeA==,type:str]
    LETTERBOXD_USERNAME: ENC[AES256_GCM,data:ox4BpQJVclRC63g=,iv:QOFXYwwUUA9JHqx+VEhvwqPLDS33HXRSMKXv49JaI3g=,tag:gewr1XKetGBHGkA5FUQYMA==,type:str]
    LETTERBOXD_PASSWORD: ENC[AES256_GCM,data:CmH6q5DZukHKJnI=,iv:WNc/W36BQH0eETSkYwrP7dSZqg9oT1IIkoxTyeGhxks=,tag:i2Ls5KkmujSQ9pvxWywp1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOHFaWnh6UlpIQU0yV1JK
            NHU3ejJsVkliNTA4Y3lWMzJTM0Y1UUR6YUQwCnA0Mm90ekxJclFKSHAxenBtODZW
            blRUb2tndmxrTlBYQWhHRlVaRWg2ck0KLS0tIFJ6cGlqV2t4ZHlFQ3BjQ2JtTVpU
            UzJrQTlDVXExZjVkZ2F5YlAydDNDaFEKf+aHU/bleNA/dj9Mt1MCV+RB/SJ+bybN
            nyEyeYNjV1O0WcetVfw/AtyLd0u+fe/0auCMLYGNe5VHMl9jN8A11A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:S4nz8xpBN2Swj0BpHs3WuWNVS705mUoeghEQQbC96eEClVkc9419Vmd6Srvk990HPPdno3f9xDU7YZQr6r+KZb7bPiRVeN0waMq9QRz4NvqT/0KS+rJJeO6DyNNyKscrhTS+I7Ycn5RCBC4Cz39iMB8xHA7/W1cNNLx1C5AmEmE=,iv:wmMd8r7hKPMGv3yh9/IrDVznWj6bLC5zSISFF2Zy3EU=,tag:Z7I7936JhXIMuEUvLn18Rw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
