apiVersion: v1
kind: Secret
metadata:
    name: mcpo-secrets
    namespace: mcpo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zX0wYMx28c8e6FmsUPrKb4p4MTNHMDWFevfUIEvc0w==,iv:g8HmVakLvAIrU38bbDN5t9wtRVlfsMRzO80Hf0fi8Kk=,tag:HVuI2Xco4EHjUJbXSpRTYg==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:QjGA18mlXbIjpOKazzAhAOoOuIK09KmHbP21eI2t2uUL5PXMPknHMg==,iv:zFGc87HCnSZISC+LSQCQZPQZeol3grt1AdBeJn/+tTw=,tag:wo0KT16h4QiAYMWN92pq3A==,type:str]
    TRIPARR_DISCORD_TOKEN: ENC[AES256_GCM,data:g0a3wypBCO4LO6TmfRKOCUvfLRbl1OSbGXUj0k9ebg0VhHnGu03xz2bH2Rw+qsGFaEff/EBId2geOJz0ymJuPiUmEiXy1NAS,iv:2TwzsF7WbzqOGTjHIPw7JNf631q2Sqg+GkdXhPotJHw=,tag:12zhR2STNgaU1wb8Ghw34g==,type:str]
    #ENC[AES256_GCM,data:HOHk2iymvQCdYPgrc0EaVPy/GpIFYns=,iv:08/4ToOyEHq+kMiA7OgLK9unHZikLelL2c3B4PQ9s78=,tag:UbtBKds0GkI7wQb2ICqtTw==,type:comment]
    GRAFANA_API_TOKEN: ENC[AES256_GCM,data:tsz5L61YJRGdVaCWxnjYB4br+FLU5fF89BjDhzIi3FCBqWqDVQ/htR4IR2Aw2Q==,iv:icTAoMMgJ8fzRk7KGxPFHQNa9jiPx9w5vMXxZtmb7hY=,tag:Pf6BRgb+ens0yDUD49eDDA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:18//vFeuS27Ws8Eqyi/Hsvr47jQG96rLU7TWoqhIbVMlWyOrtxm0Skv5/K+sL1o9HJrFChvwg31tEt0zsSZ4tj0D,iv:RJYQS/n/PuzMPYX4F3r/RnQWh9Zn9hRRztAtHV/WxMU=,tag:q7PIe4okEG1doGLQmfCQ8g==,type:str]
    #ENC[AES256_GCM,data:ARSsZwY9KGZnDRpz8DBF2Ta4tq4nG2CbpoE+,iv:IqqhxqOCEZqKvcPI4B6kucInkB1gG1saS/iJ/tj8U0g=,tag:5AWFGc4BjgiJ/alEq/nw6w==,type:comment]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:lbPkxgO9s4uKV3o=,iv:ePotpU0d/aIVspMjm3FrzYER/ItIpe303sepkKoqhzM=,tag:8RbjaTmlsUnrTjATT7fSgw==,type:str]
    LETTERBOXD_USERNAME: ENC[AES256_GCM,data:oBlMcAPDJcJ9iWw=,iv:5oJYVfK2B0HtXPC7VcUl+OLIlyKYhHpblaigQ/9fj00=,tag:zL3HMwvxSO5OGkN4morbMg==,type:str]
    LETTERBOXD_PASSWORD: ENC[AES256_GCM,data:/brML2hoDifqbfY=,iv:aGFt1iMcmWyHlOMLuGdASF/nOz/mGAd/dRJ1AU6N6Rc=,tag:GP0pzoqKT2G82jcCJpKvhw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZUJiUG5TM2QyT1NpMWpP
            bndUQTY0aDBSakxkT0Uwd2dMVFhzbW5BcFIwCmorNHdIejM2N2xnOFNCb21OMGE2
            YmlMeWVaaWNhMmpSSERadHJFNlN6SkUKLS0tIDBHVTVmWDhndGhUNzNiQlVrYWNx
            RStCbC9kbi9reG1kUzREY3JybG42MmMKwoNjMPusuK+/9kgWdYIAvK+KI5SB9oXD
            v2v9YggX8Dk/xmwzPlPPlHNpXY31kMOxQKfhwAFsLlbpzflBym0qCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:LLlXBdcnDVlouJHDloTVQVhtHuZcPAw42mulnp3t97cKl+U4v8ThpNUPHlgX2b+hQKG0aoknfSfDxpS79MNgZaer4bW7N0lmOkWeTM7pj4yXTFrLAG8PsV0orWWUSceUnKT4w8botMs2vfpma+hgFKWQlSuyMatASVTsM+yBi4I=,iv:KiL4G3l89gq44LiC6kFmT/aah/z/BxuEH+CrbzDQMEU=,tag:jiIX75FDYROuOlJ7WZgjxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
