apiVersion: v1
kind: Secret
metadata:
    name: mcpo-secrets
    namespace: mcpo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/2W4jEHd7JoJeiJKTxmBYMwoW6fXJ3XWe1hyoxGs+g==,iv:WZgM0MXEQI3kA06OB1Kzeip/kJXiwNn2x+1UixZT3cM=,tag:zFcZ/QK6iWPqDKdVhVfQTg==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:E2Kw0v6J6Kd1+hq8KCng2vwliNZADR3tnkjibQ6B1qxrDcHEAsppsQ==,iv:qhNRPqjRLhD8vs6Hnjg4qtwKOnt/ftjFJoxd9QoyQWM=,tag:fGnFmByCFTYNDOdnld31BA==,type:str]
    TRIPARR_DISCORD_TOKEN: ENC[AES256_GCM,data:ToC8OzD+V+j6T56dI7SvfI8jCRiasDQgOYid8g0wplrFfGqCwbFwkLEd38z/SmWX5Ewb9gE2qbCaDHZEygzfwFeZh8oHESgC,iv:agt0r9sPNshvUTuMFiwNmzjbH5kf2xpIe/Yx7o8CBHQ=,tag:fSmqGEVhBjZEvgRsOkVvLA==,type:str]
    #ENC[AES256_GCM,data:PhySyA5yHYUI8bVyisoRoF+HBA7iiw4=,iv:Q5pepPoY/rIOxxh7Zh4EMyK+meT5oAzvAujoXiVscnI=,tag:LHG3QRgnXuW62Zq0gXRaOg==,type:comment]
    GRAFANA_API_TOKEN: ENC[AES256_GCM,data:PVsdtnvMr07QpmhW+VvNxxfLhBxIirtgLdnWR7vGCaR6VPUUU+h37koQWVVqRA==,iv:ChkbVn+o5MSlB55zrOgkf8R4UrmwZwqeAW1OXf1wQIY=,tag:pYB5rIsMRhSD1cW0gp71lA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:q50ELpdrfS5ctuj1LboiXYBcKk6qHSbdIqmdWqF96oYqRGKX5c0zdlKqZNblvhXgN3u54gLKA/b6ax/FgZlvhzNa,iv:DEyxj1cL9agRgcQdXMOGc0LIlqIhFsELb8KcWIAoTgY=,tag:inNHRHtO7h57kOHWpxNqJg==,type:str]
    #ENC[AES256_GCM,data:bZ5Zu0H11f3NWkWvcbCLsLqYhrML8yoTFLHp,iv:6lyFKwTAysQ+ENQhuBnWRFmp6fdGXOu9jhFHLvLjYC4=,tag:p4mUqFTCACmlP4XpogjYag==,type:comment]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:yNqwZ8gIsXiSh5o=,iv:ZxMso5lxo10VjIGYxuLSpyl/bJfiOzWGMf/owedSHp0=,tag:mYsKWxBiYNB8ijjqOmS2fg==,type:str]
    LETTERBOXD_USERNAME: ENC[AES256_GCM,data:EEUd7K5eBYpIYNw=,iv:pP1tw9De5MBGwZruQ10cpNi7YTA+Edj0bcoDLL1FaJc=,tag:FhpM8Ox/I1AT84KiIAVolw==,type:str]
    LETTERBOXD_PASSWORD: ENC[AES256_GCM,data:gKivJp5NTi4Ud/M=,iv:aRgBCeOyH/4IhfQlbh3WFCCjov/7nCC0XRyKw09VBws=,tag:9O1fJXcjKrHhpC9JSATYog==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcEZseHBmbFN6R0kvYzRS
            MVFOOGdROVhpWHpNYjdWb1BHVzdpb29lWGhrCjlCYzdoTUxIUzVjSDNDZFlmdytz
            S2hIMFArTHdwNzdEZzloU2U1MCs2TWsKLS0tIGd3WU5IQlRmVDg4SStUOG9nZFBm
            bW5OS0szZUdNa3BrUGZnQUQwdWorTDgKrhHxzsnGy8cEujNze+j+ePKnc+RLjoOa
            qEdNb0WNU87JRExQutXBPRm+isJdOVaXGasp9TzbqYOFno0wg7WdTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T17:38:02Z"
    mac: ENC[AES256_GCM,data:emPZY8pyf3xRBBG6CussO9jkKZwWEnOGGmjXeFd7DII8YxlE1FEeDD0ztTZEmSCSIJl9QcANKarafqdF2yP4aNldWnq1Me/n4OOl+ZiLzkwR0MVtiQFh52IeU6RNs9VHNH/AHV3II3pRqvLUxdq4xJ61cRF5AXBapemTb+ncZ1Q=,iv:WkDj7trO+5C2E3K/0upGuz2rD3GluIdCwTeRmHDhjXs=,tag:dGL/a866C/9t8CQeSO99qQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
