apiVersion: v1
kind: Service
metadata:
  name: mcpo
  namespace: mcpo
  labels:
    app.kubernetes.io/name: mcpo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: mcpo
