apiVersion: v1
kind: Service
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
  labels:
    app.kubernetes.io/name: truenas-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: truenas-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
