apiVersion: v1
kind: Secret
metadata:
    name: truenas-exporter
    namespace: truenas-exporter
type: Opaque
stringData:
    TRUENAS_API_KEY: ENC[AES256_GCM,data:3wCDGFm+8aRvDXzIykEDSySiCZU9i0MFUZtLDLL5SVMA4Wg6Q1drGxm2kxMeEKgh3jrTfvcH57G7+6us2quSOQcq,iv:qcbezkQOy148NqVfTRy4keZV6xohotZu727xwvS4T00=,tag:fuaFQB5SF4xMxexCK8+D6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVm5rT3ZnT1gwWm9rSlR6
            TWsyOUNCSnZldHlMeXhGVncxRUFGUXY3aVE0CjNHNFAvcW5IOThXNG5ucVhaNHl2
            Q1pOTG1icU1LTzVsRi9GU2VPcldaekUKLS0tIE9QRUM1cjFJWnI4R2szTXNWWTFs
            R3g2WG1QMmt5ZzFiL2NoNGpiWnVnU0UKRQy0Gw1J4CsfYs+ywk8NLezUJkhT9bca
            B4DSikeuYZTeOsVqAPK0J0h74YYT4WwI0ZTHoEoWyQqABppQwZuwqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-31T01:01:00Z"
    mac: ENC[AES256_GCM,data:pyv3s6IuO/uLyi6GInIjoh6ouXh/TJAC7uR3YVerQqZ+yvOPh3mummfip8xTsW9LSAGOemNMkmnUKV8FOq2uTotJOLSsNWNjTN8dFc35s4iQbIvamLMIkqIe9i448NXWPXDHdNNjjEvwBNVq2R1gA8s+vfCAfPrgCuK/A3XQmm8=,iv:Djl08gf1t062wFCMzTldoyU8+f/JiUGZMqYXCeJzrnU=,tag:xDiIuibEsPJCdW6iJSb6+g==,type:str]
    version: 3.13.3
