apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:19kMsMIJs0ceo+E+JdWJNd2DI+B0yNiWXxVOn1aKRf0qQ3enLMZrJiHyrJUJuFEdXWhf+nqkCFnBypn47E6iyMG7aOljIBGLqjwGBdxEMKrs4z7t0o50ExUqNs2c4YPrb9W8qhU97mUs+LOdGN+unES/Ke9OH0dmFneM1si3q+LyVnL+x2jDA5W9ofZTfbXu71LJhoASi/lBxWJN8FhFyQFUQ/MfALlSy87mU5i6NvzG4R0Yz3/pAGFzJ3JAO0n/uldOhfB2pRcJZbgmNZAEAVx3/C5u/s+UTh2z8tS1MXFHWBbouSs7xsEGTEDiEux1VhkRa0kQMkrT2ZoDToCOdahooBW/4QC51pcDVD5V59MyidOEJb1+Yzh/tRvlvfQQ,iv:53krKlkjUsyiDj+8gATTMGsj7tXLB/ggb8POBSDWh1c=,tag:xi/DgTSudKARQqhYOD/Hsg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Tpjk7yqddj2ofKJUrcruDmfXImtqxT5v/mHjnAgJufMH+0Cc5qsZX3txBnr5Z28KvIxclxVP7Vm4sJ89jlN2hkDAOtWh+piKn9brSuKS4RrvYm61b83ts0BAna1rnSs8Z3KXyrT/v/gJFXd0wvq6K2V0S6v2lCmFSq6iR3jDvmIPBSs06gFPKqz4DziNvBHD+00inI8z5krZShwlgTAY8dRGoIoc30NGpbecROd6elPCKTkKkD2uoKqD7agObcGJ/mrranvYxVw8HW25AA==,iv:/Ya8KPk9B3sgfwvkvjPsk4s1LhBJuCLJBactXSJ8C3M=,tag:8w4F+oihbqXQQq8Jtmr/Ow==,type:str]
    known_hosts: ENC[AES256_GCM,data:dneJchG66OxfggloXjhYO6J+vUE0/Bf/GDCWosH7mPmgdDydKrFRxd5qdCEhr9AFmd8l+avQYnW1w3GjXTigsEiSXkkUi59//482DDlj/sV5NVVvXLio+ak+pUN91tfCdFUg1TdA+U01Yz+SjcKdCDL6Egk40pIl5yoXs1c4N0he6rUiGi72wSZZZDKO5zAA9eJHiWpS0DpspQCyKCEy+m/pBjEvB+ZZVdzN,iv:evHp3qQPBMLo4eBiOEU3f29TYYi5DPhNbYWYjgZLR6Y=,tag:QiPww73Sg/wrnhqes7C3rg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZitvL25XWk9XcExWSmZ4
            ZWdDQTF1bHpqenM0M2NwZ2lsbUZkaGsvcnhNCnl5RmREaTdVWXhQc3NZVjdhcjJp
            dFM1VW9zczJVRE54d0ZoUnB5bUlUOTAKLS0tIDZJWTVOR1RNczJVOVBla0dleXlL
            blpqSUpOSkRhRmFjTkVvU2puc0Ztd2MKM3ZrLqpqUo2zyVGUJDggNaplOKe7Gc1i
            hUXbqn3E8AfHutkZEB2u7RFCV91S7+ZJa5ZmdFPk4h02ds31Wr8QYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:20:46Z"
    mac: ENC[AES256_GCM,data:0mLz5e1GaoZHV1Pi3ifnfCfQBS/PEC8RdaDKlW/SWbT15KBVWaMSUD0KZzzwPC2cuV2sF+viyYuC2FhKLukSNtEMcKzsV8b/ltKejQrqHItkObbSwftu9Cu/x2TSFYmG/QMzTkbn00IZiBwbLsbWMs7hqLWCecTOL2zHXbM/aiw=,iv:xZ6rC/ql+TbLrXjTgZd+1a3zwdakKXmfe3VTIKT6xA8=,tag:3NaNIlAGqTemKPkmUbL/Uw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
