apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0EQLMhmKjBsFygBBeTvOUcLIZMOq0pbNe2tebqe8BEWy0f6MKKoFrHuhZX+o257UuDqjjVtOu7j6d3b3DU2UqOR0TKPtzTQCx78G7UdeLuG0GuLTALZSnqJaBHO0B9BFF2BWOLpSAgcuaVpNXpEcRo/flFDjP/O1gDz2VBTbp8KC9BMfaF48Z1S1+RnKzQqg5J0FJjre8MI6Y6BRxLnR+3HEzwaA2q/EugufInotg3JEQndyjPkuMAJLdAyByCiv+cd7SLI8lXLdEYVv0vGIjcJFL0FJvAUuKmYgeirCe5NDFzurGCEfuLbWONvdVWeiGCnUetoQ/RN1iwzpi65tJAZGyjCqUhUWpbUzahWa2sJRI6gUYJ66da5ImSgE6ced,iv:GZ7hCF2MCXTn9k/4xqHXXP94tuOV4/1WhNkkNwIpkP0=,tag:1qskd7n/j2IlsawzpHTkVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NVqLRLutJXyojn14OKebhJ9R1LO9xrgnHdu6La02X6g5J8Tg8uMILnLKg/dnzo8z9aOqZYlSrTfSWsfPvZoGLuq0MCWFZXnWuDaoqzJQ21m0ZLSABUayvqneAkBC/MpS9mB4XOfeglzlTcIYoC4qr0pDho8CcLr4PkLszLp4B7s4LFseCzl2zv7HEHP07lgQIFG+3d0v8Au+H6kH0awHNhzUu42GNkCHk0EmtK9ut9Y/0JvfLAGYcDweNBuKDbQc+LBUDTRyR1E4BjUvDg==,iv:IqNwWufqYc6FAA6dcZ7MiFV/w7WHB6OPmUnH3lvMq98=,tag:ZUYJgGBFHLXQiGQXc8OkVQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:dmC6Mhvo8VgDN4dKwtAQdqs5wN2/LcI6G81jyl6HUfbUGHchCcK/THGcT0fbL7Ybi7b21BD3KHk6aQeahwZeY4Tu17LtSZ70lt9dFwLO/BbOK+ybSB7HCYecujNT++4EQ2RoQLvw+pQ5Z1X6pzQYc5/Yq4UJjY4Sv5sthC2JpjzpRFID/0Y3KyUTWqnSmkl4h6A9NaZfdt5aCcCZhVGgIadFT4Qh0FlFBVlB,iv:rVCl6bX/O9uzlyuxgjW3KFuR8DELPD1fJOc/tL9vGiI=,tag:FC3DiAzaY1p0/NbGPPZyzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd1lUNXlMVjB6cW9vZ3Yv
            c2tIYkc0MEZEVnYwZXhUdXdnZW1jNi96VVU0Cm4yVzAwWlpiT3pXMjNaK3BERlJJ
            cGZwNUxPTEZxUXVSSnhkQXR3TVdTMUEKLS0tIDZqMExvN2g4ckgwK3h2MVRlUzd6
            SkI4d0g1U0xMdThFMThuMjVOMFBPZ3cKGNcivoG3v55PoKX4EqUy3LKHlko33Khk
            oNVL0oj+/1U2hiB50e9VQN3H04y8GzuhGLB9GA4R+TXxc8vhZArv/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:14:47Z"
    mac: ENC[AES256_GCM,data:2kuaiFrGIwq1cgzvVL03lmt4aIzJ3NVD9KaepoTkB6b4QAe1k3f7NWRFv+QXnkV3hI5AKshX3Fmt9ZhufiPvpsobEEizMIoDZlz1uUD6FGNVwpp2/P97jmt4DNuHoBPy9l6/TKSY2mUAi8QI9O3AT1ieXZpcz1A8awPT2UFusHY=,iv:3Rw7u5FV8c6OrB0iaZrxoGg2pqpsE0dG5fSLE1yudbU=,tag:2SPFwiteWsDPQdL5+An0Yg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
