apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gGcFjRbGxXAhdTulUpGf7rcHLpbWK/G/VCpNw8+rPsQqjYwBFovQBgnrccrOyemEI7BVkorWgV3qgxhMDykURt3eB8rqUqC1ESAogrxyagu8aXfCJj/F+vkz1NfB5rgqpISX8w9114xOce5UzIHwoLJ0ZEtBoq28sk5Aqd5orh/LkqSYRmel9Plc8hGEnYRTByp5kYugEO867yz09+ayOrCOJ1T3EhOiobCJ6bIc31r9kgxKG9eqE4QJXDCs7fp2vMRBiXTK+DUmuvp870r+FgoGC8dHLwaPsZOxwfaPKy8VTdyMxqzexno8YKeBoMlYQSYLcPwoxHMLemBlz5sPjvbxmwUvGGIFN5n+IAIK6k1cTfeszfLbSsK812wkMVnE,iv:CMOiZQve3+VqZqgfro1teFUjyzNn06gUTr4T4FU0t6g=,tag:vmS2cIYDyTNF6BpaflUG1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:z0lDBmNmk5JXl741Vi62NaskwOcymXEaVER9zx8m4h9Relwyf2c30o0mdcQRCDWj9kXa+D+3WmDvjoyB5HAf8+unVQXmdcJ/HdGNs52Tr8qzQZQgMNUROAo9GCAj1IXkNRWXaiS6dQWdJ14HID4EzhJkmOzM3BUASGfNFgEuWxZrz2QJEouWvfdn1xMtSJBAnajs7bAATLGAIOfgMgMrxwHJRe9EAbk4tumsGelY+95tw6EkORsR6xrx8R3LZDfuf1da3jR7sw+TiUZeJw==,iv:zwoHizOcXGfh+oyAhg7x9Eq0vImBwHIcOREot2zC/GU=,tag:Yyf81iIA2xSGOGOAE6EiEA==,type:str]
    known_hosts: ENC[AES256_GCM,data:V0AFCPepzem0QHg4gXVsjZzrJcX7ujVj8eIYzWTrkEedbKQl9FTwgCX7gTXn8bD7LxvNpxB6eqtHGl+JDBR88rde69IZkj61G4rdFMxPbURn4PjUXB4CY+ipoUyQSXZv59afQqYcY+rN+bHDqeP0XAh8awvbOirQAfUb9K8ODBUr6xffwIS+2K+iTJKTbHznT3O7NoI4JVdB52JfFzGDRud9s6hBtF32S/Zo,iv:IYoHb2CA/YxpBsD+nh0ak/8udmT1HzfPbRUYxXMQDmM=,tag:rXJDjlk3r8HXKMdRp70Urw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc3g5YVZwZk5PVDVyUnZl
            WUdWWXFFaG0vK0t6MzB0cUFjdTBrQUJlZXhFCmxLcUpnL21IUlpFa2toL0tyOXox
            b213Zm9ndUw4UFZ4NU1kM2lLN3NvOUEKLS0tIFlCZTQxSE9hQmFRMU5vcW14bFV3
            a25kenVhTjlVOG8xbzduVTRnZllCdEkK4eHCDXVRnC5EjIgUWaUIQuwc2rQa8DTs
            DmGJhrp8UQSyiVqsB8XVfUqiKbIOow1qidRwn9Hcf2IL4P0rsOUBIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T22:37:26Z"
    mac: ENC[AES256_GCM,data:X3Jz67KQGOYO07eo3f0t/BYUfCtN9JiQTcrTuw/KEGDia716yCb2cwmphbFhI1JyosWJ2JHoiXmQmUhSn+fs4IjfF2wND58hh4O/nIgUQHXwtBF5Q7Y6jS1w++d5X34LBs0h9Yl7eLm83XlRxpA186Zhj8R/M8mArBPGEvRh1TA=,iv:0hxCylqGoRH6O7p5XBTB8aCVm+TWY36bl59kT+bvwds=,tag:aNXdde3HTKKd9Cph+Egs1Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
