apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yK4AYJBc8og=,iv:hH1RELebd+1fVpnYwzWQhs4EQuxTmF2XJExRw0pB0m0=,tag:M7v7Md4RhGRJxws1RRVKJg==,type:str]
    password: ENC[AES256_GCM,data:oh90jUX0tdPsEj8ch5kz,iv:NlmpQsAEdBTRldE3iSaukRw27IzK/PcesgxQAZ4VdEQ=,tag:hW/OwEpaANf2dEV1FnWJBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UUZhbC81UzlFcHBGNHEr
            MGtxdUd3SVo5ZXgzUUxTdHNiSzJWMG1iMFg0CmRqdC9EdGdUQVI0b3BnWk1aUU16
            cGtlaElKczliNU1xRW1rTzA3UFE0YTQKLS0tIHArL2w4eGszOW9aV2RPVnBMNGI5
            ekpqOGFrQ2xCbHZ3RmV1aW82TlMvN0kKpzoCs3uGI2q/Sts9KtpgDVpkrCq/LISF
            DwMOHnYsbOoyXRdDOFl1ezWabKSci4Nl2iOQU4S9tK98Bkw0nvYzuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:ae20Gni8qHsIkUH/4WLdTGtCl912Ip54U+wImyo06QknRyv7bxeHfEgiIl7JGl1nx3hdI1VzR4Gnf2uK6Qi6l0nmjSq/WrR6tnw4lTQxFXO4ZOBqyOHywi6WEm+g1/goM7NVL3Jv/sdEFX9Ex+hoY4x9Oh/ZLxGQsFCFcFWmCoQ=,iv:B5XQmJskEVyZvO74Jq5S0WtA2dvR58lXHufpdSwdo+s=,tag:NCv4ZjNyn3Ck2UMnxRQ5yg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
