apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RrOPpksOzjs=,iv:x9Fd5LKiXZ6vwjAsl1Ot4nNgV2D3/z8xwLFobOo3gb0=,tag:eUmcPhPFq30g6ECtIIM2OA==,type:str]
    password: ENC[AES256_GCM,data:mYBbfvOfXbVUx/K5SFRj,iv:ylxY0/Qe/cuxla0xN2NhaC8KDrH17Oh2ZW3bop2nw3A=,tag:DeaMMINRp5uHcM3LZ8prkQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZktRRVZQWHlBbzNKakFT
            OWNlTHJmYzA1U2VJZnJ4Z0lXL0hwdHVZUkM4CkcydFB3enM3ak94OG9mdUg1MVRQ
            WGo1SU56alAzRm9VMUhaTUtyWEVrZXMKLS0tIGhjcjVKU1IvK1FnRkRsMVNJZWVn
            ZVJ6WEhDUzFBSTRHWTlrWnNyTnVzYXMKWpy3dhBGsN/GN6jXwZUthhj8lrkoVUEe
            vG7LqAJLDcSz/TKR8RyyYZkifIeU976mEt7f4s4dGPIvnMvlenBDEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:Y0rW6gTzl6/FE4p0vM/TqxuZR7uRXtUAC1nnyPuHwtn4p+Bd7KJjHy6xsVhjfz/N8lKBgeClof5Cus3zUS+PAa21x13G9RKEG4g6tZrzjQZlvA3NqTx/rcSuFAPP/+0952YGGt2lJQo4o3ydWTLpNNwR4l2d/M3ZezFkoFZwdVA=,iv:eI6Rndnh8fD51T0T0XnNg03j9PffMXMneWsS8Yxg4Ng=,tag:BfX40Fdbv13yvELbc5GeTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
