apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wmCYow+9/k0=,iv:Ld7d/p7yT7tvQs993ezjZobJA6JznIxsA5ZprKvjR0o=,tag:2tE6E+/5nNCP8QhnLpIkeQ==,type:str]
    password: ENC[AES256_GCM,data:55o0E9Ybj5EMAh12iJ9H,iv:uxdTjeQZYoTQqmuYfGYt7NjxtFvFFKYxP6/0hyysjyY=,tag:Q6nZNtRTw5yv7Xu4PzMjOg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQTZmcGJNSnRXcDdHc0hO
            Tk8zZFZtb0U5TjR4QTVrWkc0SWsrdmFsOVVrCkt5MnQ2ZTNsMGdBUEpJQ1NOTDEv
            OU9WbEI5SkV1b3NPb3Zvd0JnbVo3YmcKLS0tIDN1STltZVA0blhTR3dHQytYQnJr
            YmZ2cUdZOUlISmZPVUViYWpsaVZEQUUK8V4Ays0frW3eCUg95ve51Ff3lzuHtho9
            btOY1hbEvm/BpJRvje6W9QZclayo5eTn+2daj/0ZA2I5jCuUI0THJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T01:39:43Z"
    mac: ENC[AES256_GCM,data:ch9qnL6NKSUvQPKqdjhqoWEqPSCrBnI7zIJjNN841g6HG0ozOGF+9xDOdtgRZ/Cz3O/iDaBRWOuNdCCR2aqB7lZSOciYhLl6H1YYZ9fnbSqpqPiJV0HubzIc1fNJOPj2kBX8388GKhj0Ba1BHKEgHhyMNm40aKKs1EMeULGHREw=,iv:EBDlY4NIcwDZu37tsu0UTLMGkocManJss76kY+S7sZ0=,tag:cubOJRHbo6iexXuUTFonpg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
