apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MNGLZd1qIVEtJ0L+mWeDrKaEh7ibKpM+XNlsZg91QXhU1BJ+WB3TceLloAB2abBT6WCcnSZTjbKMdncyBEKonFv/tZNCx7A6Oeu9UQqhKzP0P61G,iv:siSJ4P2dCoGUxneQ/4KfQ2tOvPz2ye8Svvadyl2g/aw=,tag:tJCKc8fz7Fq2RgOqMmOSyQ==,type:comment]
    #ENC[AES256_GCM,data:+/aiQ82E2Qc8md/P3sb9uZX7BRphGyQEZzE1Ghhtga/daOLXsTWabVRMZlyjS6dSnvH2WlHkDDWMDL3lFnIvYL2CLW5UobZHEtaYJTBEaNLDS+BlQumc+5sdfrFquQgV7A==,iv:PpX0f/bKcRuCBlooYKQDgBWiGrciU2/9WGu6EXI2fNo=,tag:ZjpPgmMwFDIyrAuBmf3tlQ==,type:comment]
    #ENC[AES256_GCM,data:YqDsNGlH4Od0dKVgmI66R0ZOQFVkvs0KTCG1u/BMTLdpgvUlmg/u0QW4ndzakRTswSEFZj/N6DFsh09cyf9a3lJVGtnKYF0vLGMQkix6gC1/dx5RY214qufGeRk9XeIGQZc/BHQWLVWtDvm2pQ==,iv:94qZkJtST90QkToQ7qgzk2vUeWrRHGy+1goZLCugWuo=,tag:MmkLGXJuZ3fGnEmWF72mgg==,type:comment]
    discord-critical-url: ENC[AES256_GCM,data:SqRpxHWDT2Q3szVFadsltpwEshJrdABiijQkvQ3Rm573fzx3q0Ed,iv:Ph8pT/LpBQgu5ySwDTeNedLwgPiRVSe6QsrbhQ2UNUw=,tag:kZH6VVvC5AvGqAoFCcy5jQ==,type:str]
    #ENC[AES256_GCM,data:55QOITfZ7H0JSj2WU/k2dMHw3BtmjoGckqcfztjArxln72rX0vNXNAZkpyg/4+qQHzSdFO5klR81TEKu5gT0wxN2b/J4j+Lqag1VBkBKkXU2bXX6DuABm0LwSp2GXA==,iv:opkNiXqC0AqCDiNtD31k6AubUaKZvxv5BDbDE2gP5AQ=,tag:0mBlAhpJzFBqk1utVjyFGA==,type:comment]
    #ENC[AES256_GCM,data:jhwb3m2e9f/btGf01+Cosho2jaw3T2PytkgqtuPz+CHd39fbrEOwE5cpMlVxPkyGEJhbE+2phOLhgFYTboV0A3S5yQ==,iv:DJHWZXixkqI8JIg7XW0tipEmxmlcx2ozNvS/9X8F2OQ=,tag:o/t9uRA7G2LRkz1bWWEM2Q==,type:comment]
    notifiarr-default-url: ENC[AES256_GCM,data:vfaiZi9iqmUG26v3ArJ/lqoV06myRhXZrEoEBxobTASlXYVXPiz6o0GKMbAanMfBoKdjksFfTCb/YgWIKZmd0lv/g/9/Ehg=,iv:ueW3g3K7c4shwCs2XJQxRU5haLEs1NWh72N0CHRaoUo=,tag:+qkKyj1GarWx977k+4P6OQ==,type:str]
    #ENC[AES256_GCM,data:YslJRFTQgcIjis6wWPEO3rm04edcdQ5KkN4wnWEg82pi4sxPtuveahN1u6xD7zzm1GzF86Xli7clHhg045y+CbfAHMTRTOOiX7rzEvJHNHuV2iY=,iv:C1urU7wOw00F513dXKw9OO95NusfAlJemPEaEW783vs=,tag:FmZ1hm0lmqNRLeYLH8aPSw==,type:comment]
    #ENC[AES256_GCM,data:zNPQs6rzHMuEWplzw9/gVWy/ghdbWX+sU42zLOgeLw9qmgGBi1eVcpmJ3XzNmlLln+hr+mvmoo41tA4A5zeir+FP7rtt77VLEWqHKEAtDCekM9Bb,iv:HtUzVJKYePg0K03ucTcr0QUJZdSgArDLH0as64tDdoE=,tag:ob7AMx6+Oj/zVzvI/3f0nQ==,type:comment]
    pushover-token: ENC[AES256_GCM,data:GvlG7tzLxSavf2VhZ8rF2/sTPL5s5uLnvQQNB3s=,iv:yqKBW1LIREBAlez3Z4RQnuCZscmeMvPLv8JHCbg4Nq8=,tag:d9pQ59EsmTL64OCjqvqJiw==,type:str]
    pushover-user-key: ENC[AES256_GCM,data:usOnVrgDFRSS3EDaWK67LKxMhPII22pv3Wqq7g==,iv:hTYrYiXFtb0HVfijeRBedcEPprWTqa9jvJngdtU9coo=,tag:n+TPnDVtpGkqB68SNXWAmQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSVRUM0U4NkZwZHBtMkla
            Zlp3aTVXaW85akNFSFh2aVFzbXEwWjNqcUdBCi9OMjlPWU8zbm4xK2Y5c1BVUDgr
            MGJXQ3Qyd0dxR2Z3akxjaENOSVUrK0kKLS0tIGVPR2pwcldPZkpZckpYaFdoM2tO
            bklwZE1qa0RpZmZCbWZNaXJySEpLamsKjSRJ7f0RNFAMe7+1mY2J4RXChP5ga0tp
            R6HIDCQELoIvXPpapUdVa3BpTD3Ft9VMbmxgmlCmPJrdKF951rgNOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:tqMHthPjsQK8uvcFK49vk0oNbXkVBzqTzzflegvI/OTw1IA40IJSWeEOKE7SLiI8njp6han1D7wT7Z41by1GH0eDAe8T9OdH+HfQrWHvrF+JIEKbBndm8iofjMfFBA0+an5VOH23JYLA1gomM1fZUUmwKPRedniFHzbMnX3adYY=,iv:afxC3BT+0lEYH4fPWMMtTVqV2QYwgEH930+XLCRyJDc=,tag:XCes4twQrSeRe7ECrlIzoQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
