apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:RTt1Flm5OmU91QmAf4tmzxWHZ0QsbNgcL9C1AmoTF0tVM/6vPg0+wc048GXc5eeZM/o1zBWmbPe+f7dly7HB43v9LLgU/NRONcAXzZCeh24eHKAjIFUHtzEjRVp6C1Edt9muOq1WE8j4izTWpjzwQg/SvC2tRP2StEVVQ4qzAWZO8F8QDB0e3vlWgAKvI49aIzNtNna8KVLLeFkMBar6EQBuoHLoKf+w9EUktThg58JOzsXIkVVV,iv:N+JFePM65MXVIx82VajpveR8k/Jc3Se9jLi0knE3pCo=,tag:z+BkvweJcfciuNWral6G7w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNVBFZGhDOVdFdmEyeWFM
            SUxLclNYUUFKOWt5YUw0WVM4cHczaTJMVFdzCkg2WU5XUTIxMGwyaStMRnY5S0Zy
            UGs2Q3NkUExCOXRtR1JUSmVHQ0hhdzQKLS0tIFg2NlJZY0lNeC8wQjN3TWZsRlZT
            VlQ1bDl4N3kxZ2FBY3IyT3RBTUhYOVUKF8KU+LLdSIlyLbfY4Mf/UkQlKpmZ8gyZ
            709i4CT/yKs8cl7/B5McdoK7NsfwMff133EsdWSYeDx8joawc30KbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:14:47Z"
    mac: ENC[AES256_GCM,data:3ffF+cQ7lQhtDUSoTGLx2pethsqiAZMRkFlDdgqGKWAVZ5Wt6OVpV1DIogFg06vx7iCxWiveuhajK4Bb23mlms4TuSvFF7bXF79B04yZocxJlLdxfDtL/HCYf0GkRQVSDjjO5Uv8hvdtGf18fsRsMehDWKs1t+P3UgZ3HEHWiKY=,iv:LUc7TeuIMN0EuV88SYNlGil/RRY6IMF4bDUJDMcn26o=,tag:RAe7usxEHvHWEhUqws41gQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
