apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:KL7UZEMHhDcKlg5i/ZWKB6DrHlJfIGqJVIsOAWuhAYykyN6GLsb+XzLum8K871m2w+w/D2hstKlmmNO4va2gKimFySAdfoTPLj74H62GsOSBHFx9lEFKsfw1mV3VEPU0RkhZ/8nZM+eGaaLN+O45TM/06vHqd/WwcV//cCN/nUAXVrGwIw58LYKpNEEdvGt9ZZleQfxFQofaWpvLO0pivXGkS1RVrNQRb8YKSIkOil4FK4zr5m4n,iv:YWtR2SoWPftXokbS+5rTlbhSvIzRQxI+MXUBgJMN8mw=,tag:qEuYE2ZkHdVaXZwrWxUnAA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bTErRWYxSWNyMGFYMnFF
            UVhMS0Y2QjNya25BbDVyYWlzZkFuUE4vWkJBCmprRldDQ0lsM1hlU0o2WFJVWU1V
            aDE2QWlOL3l3SmNTamtKUzhrUE8wZW8KLS0tIHgrMVVDTUZ1VXVuMVJ5eU5jUzdi
            Wnc5TVJWazd4TEo4cTZqcFJHclN1LzAKElATpOS+OCIsIQixaC7dUACb3R4GPP6a
            CQuXBU25hJd8qBHBzQgUSJ4XOkLTGFAj5n4cG8hHuFZnj2itNlzneA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T17:38:02Z"
    mac: ENC[AES256_GCM,data:XCp/WvlL5lp9vstjPKKpQqOM3k3zxoN8tbqvFZYw/GQZiSZMD2p8Jfdzyt4SkMsc0cKmAU9y4OVuCH8NvwN23vErvMwPWebmlEE6UsTUGJ5DWL6FMcBnKGCn8cgo7iYs76OnG9o4FfL7AvYpWkB4z/KTIFL/1G7wBgiBiuqsynM=,iv:EaNDkOC9DZJAU5Kzb1DlMPgFwLcggyRqapLGtIfBVhY=,tag:mn1Srix51GSYDJ+wd8kIhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
