apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-token
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:NV07jHxSYl0qb+Y1GTPRlLmOFBB5pjpWHdi6whdRDY5kHKhjCYYQTHt8oVIftdHrVAGTfY/4ILOX7z8KZIgbBi2CMvltfxKWGjWDg8Ez+2Q8X0KK1hsB6y34uNQr5/AYptUnbgRhng2hX2E+DqCb4Y+DKQL5Tn1LtHcM5j0rYhBk2B8A/0IonbuIz8jE5HK+Nb8Qb5Vz6Rcpbzamv5FCLpYC3RmTW5MD/3d53IK/YmOXSELLuZW4,iv:hbTTa0fW+2qiZuyt0dTU+KaUzwC2YotUX5AOKQ4eFpI=,tag:D+lxcJ0RE1cgcunTuFgMsw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGNMbS9LdFZMRkhjSzAx
            Ni92elZCNVFtMktBTnhDczJPNUJKbXJteW1nCkxPWWVjVkhsT2JNMWIydWlsekVH
            cnU3M1hPbUwxVkY4UU5JWTlheXdhS1EKLS0tIEQ5ZzY1ajE4NDJWckU0NGkrbVJ5
            MkRST2xieHQ3clkySHdkb090U2VLSTAK/LDcNe9tTpuMs4ZcHcDtVxslLxL50a8J
            BUWJv4J+5cYDZlA0SI0MMD8BxVqohwG2d26kFlijKM+X45HYucpQFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:65qUvg30xOgtIs5WVbgXqhrQgegAE2qhGl1VcV1K45OugZZZGnRq0SgEeloe8EZlJ+lwlb/FU6EZ7VX4339xjm+62cqn1jEH5ehy2AtLYrjIV7d+2o6BEokMRcFVfBVLaoI/CqVjSIqFCx0buKnOqgbCvRg4mSHQYw/R/eflGJ8=,iv:+h922tOF960dxW7r3DMTwgHRD43A5zqxOfexhwM7zxU=,tag:PsAZd8lpo2YNwfdbS9wbqw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
