---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - alertmanagerconfig.yaml
  - alertmanager-secret.secret.yaml
  - prometheusrule-meta.yaml
  - prometheusrule-solidigm-pool.yaml
  - prometheusrule-crowdsec.yaml
  - prometheusrule-storage.yaml
  - prometheusrule-cronjobs.yaml
  - prometheusrule-network.yaml
  - prometheusrule-media-integrity.yaml
  - prometheusrule-homeassistant.yaml
  - homeassistant-token.secret.yaml
  - scrapeconfigs.yaml
  - podmonitor-flux.yaml
  - grafana-dashboard-cluster-overview.yaml
  - grafana-dashboard-media-environment.yaml
  - grafana-dashboard-media-movies.yaml
  - grafana-dashboard-media-tv.yaml
  - grafana-dashboard-media-music.yaml
  - grafana-dashboard-media-books.yaml
  - grafana-dashboard-media-streaming.yaml
  - grafana-dashboard-media-downloaders.yaml
  - grafana-dashboard-storage-environment.yaml
  - grafana-dashboard-network-environment.yaml
  - grafana-dashboard-dcgm-gpu.yaml
  - grafana-dashboard-proxmox.yaml
  - grafana-dashboard-unpoller.yaml
  - grafana-dashboard-exportarr.yaml
  - grafana-dashboard-nginx-ingress.yaml
  - grafana-dashboard-blocky.yaml
  - grafana-dashboard-uptime-kuma.yaml
  - grafana-dashboard-cloudflared.yaml
  - grafana-dashboard-smartctl.yaml
