---
apiVersion: v1
kind: Service
metadata:
  name: media-integrity
  namespace: media
  labels:
    app.kubernetes.io/name: media-integrity
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: media-integrity
  ports:
    - name: metrics
      port: 9838
      targetPort: metrics
