apiVersion: v1
kind: Secret
metadata:
    name: regcred-dockerhub
    namespace: kyverno
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6dnumb7rKrsqIC9BjohZ+1JVNX5m1FSRrrm/7kKajul6VIHNYRawL1/MI81h8oBVTyLbmOFHIeIcyCqeR0oI6tb/6oHX21XLCm49f/VCz+oF2MbGujKNCCRQ2fwuYRB61bSlfZAVNm2uGKGuHo0=,iv:0EB1CzT8a7x0fFIPVai+hp5eGswe5njO4B5sLSljPMw=,tag:w2efHhmR1j3hn9JPGrSUyg==,type:str]
sops:
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bHZrL1Zscmx5aVdwMlJR
            VDVHTU9Zbm5pUmswMmt1Lzcranp3OVh3VkUwCmkyMkZybjNMdVVpa2tRWUk1SkhQ
            N0pROXNRdDhtRWMxWnZoRXNaWWJ2dkEKLS0tIEZsaWdEb3NCcEhlc2tDMG9VR0ls
            ZHYwdGR0b3FPaFZ2YllQS0V5US95dlUKoyQ3qC3ih43HlNR+gKs4x3bSbMDfYZ8r
            3A5WK7OKEOYzpW6dU8jX+8chAyKb+H+gohlz6XOp80YVlOMZsAdI0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T03:10:09Z"
    mac: ENC[AES256_GCM,data:94SE2yBDZjWVEZkxo4AwuiIC6SF1K5R3GXdC3bQ+5tJP3XM1p4tj0atikW2/x+J/onXQeh6GzzMnBcEs4TBYZTgCrYmnhU5WoQX9RZYJeP/NNNai/EWQ5bbCqFhk7wmEdRKKvjNNfmNIwO7CVigcWngS6sY3E2JgTWTXEqyEBGQ=,iv:RpQO2OS+xvmgRO/S5kg4LV806OBjFoPYHOpLnEThmj0=,tag:ILi8u/hE2smpSKSTw56FCg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
