apiVersion: v1
kind: Secret
metadata:
    name: regcred-dockerhub
    namespace: kyverno
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:JXVpBlbB440+pFIfWxFFynLVtXYve9Sl0N5pBy331senM9EkurFyFHlvbER/UhElySLjPW/J+bSSjtBgcgMMSboGUlXFJjxsn/RG1Xrt4uVmdpYJWMR+9rwanRQc2+KuQtS4PHvgYMXimprN+NA=,iv:awmPDI9b0UkiyaX7idbFOVJ/r5TLaJOir86vUrd5KKo=,tag:cVegy9igfeChBKV4h5LVNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQU9Eb01sU3Z1ZzFTNnRJ
            WmpJRlpGV1RjOGNGQk5HUVptVklxK2tGMGhvCjJQUVBwVytnK29TTjAvVHorVjh6
            M25Zb2RXYUZrRXVEc1hBN0ttUEMyV2cKLS0tIFZ2ZEFNVkd2amxRNld0KzZYOWhh
            RXM2eVg3R1ZlTitOQjMzaG5GQWcxZXMKVazW3Qzs/GEohfNKgIzNBsG51ncxC1hS
            QZhMDmWBZ8g5TaAwKg1+S2DfY8NfbjLn3xm3EGAfTs61PqDIdOhsYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:14:47Z"
    mac: ENC[AES256_GCM,data:jQFSWRMfW6nt2vOsCRojkpGEYOCkRaIf51C2D+2NVUdcCe6rm8Q85a3G618qitPWnzCU7DmktTZfRiYkujoLloAUru9yHmxr/AVFhJrI/DPSzus8xEBqi5KrlGvEoTMRTdFW21v3QFhZdAPkJZg/nrx/3Dg1VYNkHI6pFkcRnYo=,iv:lHeVTgxzTrtwnUbHouf6uFYldMHeJZW9SB/gaVLkje8=,tag:73Y/kAnjw8FIGa6X72fSEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
