apiVersion: v1
kind: Secret
metadata:
    name: regcred-dockerhub
    namespace: kyverno
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TOWydWHIh6gfozmfBe8Qkfkhii/xpat0UTUxdfxPi3rHcsh6qcvX1y3zaZOPoJpotODbJ2bLLkr15LMaeavxs1kHycOESyqZSeut2eII1RcGlA8Lz/ryra621k65oCBzbbMY0a9zqUBVsalPHw4=,iv:co+Bruvw9CgIWh02eCCPOTeB3JDuod5lt7ASG2Nf01o=,tag:i9e2TCLehPoMx4z4adcF/A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINUdJU0d0OGU3SStGSUkz
            QVlNUEhubkc2bEtvU0s5ZENsN2o5Y1lKV2k0CndYTWMxZ3BPMVZvQS9hb2pLdlNk
            VXp5bDc2UEZvRnpZc2pLc1JKVnZsZ1UKLS0tIEsweXcrZGxPYTBPMVJJUTlQOG44
            WEFuaVZTTWRQaUhpa0Yxc3NwYUhSVk0KMeUGCzU4yZ0QEKkervks6Updn0Ifa4x8
            pQEVYH8TsZY519LNrWjU1BcLO9ZEBmFSuojgbGROHq8PfsvW6vOgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:20:46Z"
    mac: ENC[AES256_GCM,data:9iyLvLSVSPCuc2urjpWyEubXEMyLV0+Afr1SrLbueoKxaW8/OUY58vWgEER/cGtlJQwGwNpoXau0PGkjOxpy6e0q/hnrT9nt8MOe1NfTcUw5iI4k/8lb6Eodu8sNCKhv0qwa8Nuu7n6XSBN0PhBSEz3DFPZnBbX8lG2H+IJLEAo=,iv:vVNbAZ4q7YoNhfpy7SBPY2NsAodMPeGqGlAmbpzexPE=,tag:7l5DIK7B3hj6My23OEk7OA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
