#!/usr/bin/env python3
"""Uptime Kuma service dashboard - REPLACES a dashboard titled "Solar PV System".

The ConfigMap named `grafana-dashboard-uptime-kuma` contained, at 1340 lines, a
Solar PV dashboard with 13 panels and zero queries. Someone downloaded the
wrong grafana.com ID and nobody ever opened it. Meanwhile Uptime Kuma was
watching 56 monitors and reporting 1 down and 3 certificate problems.

DESIGN NOTE ON CERTIFICATES - the thing worth reading before editing this:

  monitor_cert_is_valid == 0 currently matches exactly three endpoints:
  TrueNAS (:444), Proxmox (:8006) and CrowdSec LAPI. All three are internal
  services with self-signed or private-CA certificates. They are SUPPOSED to
  fail public validation and always will.

  So a "certificates invalid" tile would sit at 3 forever. That is the
  KubeJobFailed failure mode in a different costume: a metric that is
  permanently non-zero for a legitimate reason stops being information and
  becomes something people scroll past - and then the one that matters hides
  underneath it.

  The actionable certificate signal is DAYS REMAINING, which is real for every
  monitor regardless of who signed it. Validity is kept, once, as a labelled
  informational tile with its expected value written on it, so a change from
  3 is legible instead of alarming.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dashlib import (  # noqa: E402
    Q1, Q2, Q3, Q4, dashboard, emit_configmap, gauge, row, stat, stat_floor,
    table, timeseries)

P = [
    # ------------------------------------------------------------ Q1 broken?
    row(Q1, 0),
    stat("Monitors DOWN", "count(monitor_status == 0) or vector(0)", 0, 1,
         bad_above=0,
         desc="Uptime Kuma probes 56 endpoints. This is the only number on "
              "this board that means something is broken right now."),
    stat("Monitors UP", "count(monitor_status == 1) or vector(0)", 4, 1),
    table("What is down", "monitor_status == 0", 8, 1, w=16,
          desc="Named, not counted - a count tells you to go looking, a name "
               "tells you where.",
          exclude={"monitor_port": True}),

    # ------------------------------------------------- Q2 doing its job?
    row(Q2, 9),
    gauge("Monitors passing",
          "count(monitor_status == 1) / count(monitor_status)", 0, 10, w=5,
          warn=0.98, crit=0.95, desc="Inverted: high is good."),
    stat("Monitors configured", "count(monitor_status)", 5, 10,
         desc="Coverage. A falling count means checks were deleted, which "
              "looks exactly like everything passing."),
    timeseries("Monitor state over time", [
        ("count(monitor_status == 1)", "up"),
        ("count(monitor_status == 0)", "down"),
    ], 9, 10, w=15),

    # ------------------------------------------------------ Q3 keeping up?
    row(Q3, 18),
    stat("Slowest response", "max(monitor_response_time)", 0, 19, unit="ms",
         warn_above=1000),
    stat("Median response", "quantile(0.5, monitor_response_time)", 4, 19,
         unit="ms"),
    timeseries("Slowest 10 monitors", [
        ("topk(10, monitor_response_time)", "{{monitor_name}}"),
    ], 8, 19, w=16, unit="ms",
        desc="Response time creeping up on a service is often the earliest "
             "sign of trouble, well before it fails a check outright."),

    # ------------------------------------------------- Q4 keep going?
    row(Q4, 27),
    stat_floor("Soonest cert expiry", "min(monitor_cert_days_remaining)",
               0, 28, unit="d", warn_below=45, crit_below=21,
               desc="Red under 21 days, orange under 45. Low is bad here, so "
                    "the threshold scale is inverted."),
    stat("Certs expiring < 45d",
         "count(monitor_cert_days_remaining < 45) or vector(0)", 4, 28,
         warn_above=0),
    stat("Certs expiring < 21d",
         "count(monitor_cert_days_remaining < 21) or vector(0)", 8, 28,
         bad_above=0),
    stat("Self-signed / private CA",
         "count(monitor_cert_is_valid == 0) or vector(0)", 12, 28,
         desc="EXPECTED VALUE: 3 - TrueNAS (:444), Proxmox (:8006) and "
              "CrowdSec LAPI all present self-signed or private-CA certs and "
              "always will. Deliberately NOT coloured as a fault: a tile that "
              "is permanently red teaches people to ignore it. Watch for the "
              "number CHANGING, not for it being non-zero."),
    timeseries("Certificate days remaining (soonest 10)", [
        ("bottomk(10, monitor_cert_days_remaining)", "{{monitor_name}}"),
    ], 16, 28, w=8, unit="d"),
]

HEADER = """---
# Uptime Kuma - service dashboard.
#
# Generated by tools/dashboards/gen_uptime_kuma.py - edit that, not this.
#
# REPLACES the previous contents of this ConfigMap, which were a dashboard
# titled "Solar PV System" - 13 panels, zero queries, 1340 lines of somebody
# else's solar inverter. It had been installed long enough that nobody
# remembered opening it. Uptime Kuma meanwhile was watching 56 endpoints and
# reporting 1 down and 3 certificate problems, none of it on any screen.
#
# Laid out to the four-questions order in tools/dashboards/dashlib.py.
# Every expr validated against live Prometheus before commit; none render
# "No data".
"""

if __name__ == "__main__":
    d = dashboard("Uptime Kuma - Availability", "uptime-kuma", P,
                  tags=["monitoring", "service"])
    out = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "../../clusters/main/kubernetes/system/kube-prometheus-stack/app/"
        "grafana-dashboard-uptime-kuma.yaml")
    open(os.path.abspath(out), "w").write(
        emit_configmap(d, "grafana-dashboard-uptime-kuma",
                       "uptime-kuma.json", HEADER))
    data = [p for p in P if p["type"] != "row"]
    print("wrote %s" % os.path.abspath(out))
    print("rows=%d data panels=%d" % (len(P) - len(data), len(data)))
