#!/usr/bin/env python3
"""Shared-stage drilldowns hanging off Media - Environment.

Two boards, one per CONTENT-AGNOSTIC stage of the media pipeline:

    Streaming     Plex, Emby, Tunarr        - delivery to a human
    Downloaders   SABnzbd, NZBGet, Deluge   - moving the bytes

These stay shared-stage boards because their metrics carry no content
identity: plex/emby session metrics have no media-type or library label, and
transport queues are content-blind. A content-domain split of streaming
CANNOT be built with current metrics - that is stated on the boards, not
papered over. The domain-visible face of these stages (each *arr's queue and
grab rate) lives on the four domain boards in gen_media_domains.py, which
replaced the old Media - Acquisition board: acquisition metrics DO carry
content identity by construction (each *arr is single-domain), so that is
where the domain cut has teeth.

All exprs validated against live Prometheus before commit.

TRAP FOUND WHILE BUILDING: deluge_free_space returns -1, a sentinel meaning
"unknown", not a byte count. Panelled naively with unit=bytes it renders as a
confident negative size. It is filtered with `> 0` so the panel is honestly
empty rather than confidently wrong.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dashlib import (  # noqa: E402
    Q1, Q2, Q3, Q4, alert_table, dashboard, emit_configmap, gauge,
    row, stat, state_timeline, stat_floor, timeseries)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "../../clusters/main/kubernetes/system/"
                         "kube-prometheus-stack/app")


def hdr(title, why):
    return ("---\n# %s\n#\n# Generated by tools/dashboards/"
            "gen_media_services.py - edit that, not this.\n#\n# %s\n#\n"
            "# Four-questions layout per tools/dashboards/dashlib.py. Every\n"
            "# expr validated against live Prometheus; none render \"No data\".\n"
            % (title, why))


# =====================================================  STREAMING  ==========
STREAM = [
    row(Q1, 0),
    # An exporter that stops answering leaves every number below frozen at its
    # last value, which looks exactly like "quiet evening, nobody watching".
    # One up-strip replaces the three per-exporter stat_floor tiles this board
    # used to carry: same guard, every target, plus the overnight flap history
    # a stat tile cannot show.
    state_timeline("Media exporters - up/down history",
                   'up{namespace="media"}', 0, 1, w=12,
                   legend="{{pod}} {{probe}}",
                   desc="If an exporter strip goes red or gappy, every one of "
                        "its numbers below is stale - and a stale stream "
                        "count is indistinguishable from a quiet night."),
    alert_table("Firing in media", 'ALERTS{alertstate="firing",namespace="media"}',
                12, 1, w=12),

    row(Q2, 9),
    stat("Plex streams", "plex_active_streams_total", 0, 10),
    stat("Direct play", "plex_active_streams_direct_play", 4, 10,
         desc="Free. The server is copying bytes, not re-encoding them."),
    stat("Direct stream", "plex_active_streams_direct_stream", 8, 10,
         desc="Remuxing container only - cheap, but not free."),
    stat("Transcoding", "plex_active_streams_transcode", 12, 10, warn_above=2,
         desc="Expensive. This is the number that turns into CPU and heat."),
    stat("Emby sessions", "sum(emby_session_active)", 16, 10),
    stat("Tunarr channels", "count(tunarr_channel_info)", 20, 10),
    timeseries("Stream composition", [
        ("plex_active_streams_direct_play", "direct play"),
        ("plex_active_streams_direct_stream", "direct stream"),
        ("plex_active_streams_transcode", "transcode"),
    ], 0, 14, w=12, stack=True,
        desc="Stacked so total height is concurrency and the red band is "
             "cost. A tall stack of direct play is a good night; a short one "
             "of transcodes can hurt more."),
    timeseries("Transcode breakdown", [
        ("plex_transcode_video_sessions", "video"),
        ("plex_transcode_audio_sessions", "audio"),
        ("plex_transcode_container_sessions", "container"),
    ], 12, 14, w=12,
        desc="Video transcodes dominate CPU. Audio-only and container-only "
             "are comparatively cheap, so the mix matters as much as count."),

    row(Q3, 22),
    timeseries("Plex bandwidth", [
        ("plex_bandwidth_total_kbps", "total"),
        ("plex_bandwidth_lan_kbps", "LAN"),
        ("plex_bandwidth_wan_kbps", "WAN"),
    ], 0, 23, w=12, unit="Kbits",
        desc="WAN is the number bounded by the uplink; LAN is bounded by "
             "storage and the network."),
    timeseries("media namespace CPU", [
        ('sum(rate(container_cpu_usage_seconds_total{namespace="media",container!=""}[5m]))',
         "cores"),
    ], 12, 23, w=12,
        desc="Read against transcode count above: CPU climbing WITHOUT "
             "transcodes climbing means something other than playback."),

    # Q4 is deliberately short. The Emby library counts that used to pad this
    # row were inventory, not capacity - they moved to the domain boards' Q2
    # where they are reconciliation signals. `avg(tunarr_channel_duration_ms)`
    # is gone too: an average over 26 channels hides one collapsed lineup
    # (moves the mean ~4%); the TV board carries the honest shape, a
    # count-below-threshold stat. A shorter honest row beats a padded one.
    row(Q4, 31),
    gauge("Fullest media PVC",
          'max(kubelet_volume_stats_used_bytes{namespace="media"} / kubelet_volume_stats_capacity_bytes{namespace="media"})',
          0, 32, w=7, warn=0.85, crit=0.92),
]

# The Acquisition board that used to live here is RETIRED: its contents were
# redistributed to the four content-domain boards (gen_media_domains.py),
# which is where acquisition metrics' per-domain identity belongs. Its two
# constraint-3 violations (max() over sonarr/radarr/lidarr rootfolder free
# space - lidarr had THREE folders, so the aggregate was reporting the
# emptiest and hiding the full one) died with it; emit_configmap now refuses
# the shape outright.

# ==================================================  DOWNLOADERS  ==========
DL = [
    row(Q1, 0),
    stat("SABnzbd paused", "sabnzbd_paused", 0, 1, h=8, bad_above=0,
         desc="A paused downloader looks identical to an idle one on every "
              "throughput graph. This is the difference."),
    stat("NZBGet paused", "nzbget_download_paused", 4, 1, h=8, bad_above=0),
    alert_table("Firing in media", 'ALERTS{alertstate="firing",namespace="media"}',
                8, 1, w=16),
    state_timeline("Media exporters - up/down history",
                   'up{namespace="media"}', 0, 9, w=24,
                   legend="{{pod}} {{probe}}",
                   desc="Replaces the scrape-targets-down count tile: same "
                        "guard, per target, with overnight history."),

    row(Q2, 17),
    stat("SABnzbd queue", "sabnzbd_queue_length", 0, 18, warn_above=40,
         graph_mode="area"),
    stat("SABnzbd remaining", "sabnzbd_remaining_bytes", 4, 18, unit="bytes"),
    stat("Deluge torrents", "sum(deluge_torrent_state_count)", 8, 18),
    stat("Deluge peers", "deluge_num_connections", 12, 18),
    stat("DHT nodes", "deluge_dht_nodes", 16, 18,
         desc="A collapsed DHT node count explains 'torrents stalled' when "
              "everything else looks healthy."),
    timeseries("Throughput", [
        ("deluge_download_rate", "deluge down"),
        ("deluge_upload_rate", "deluge up"),
        ("rate(nzbget_downloaded_total_bytes[5m])", "nzbget"),
    ], 0, 22, w=12, unit="Bps"),
    timeseries("Queue depth", [
        ("sabnzbd_queue_length", "sabnzbd queue"),
        ("sum(deluge_torrent_state_count)", "deluge torrents"),
    ], 12, 22, w=12),

    row(Q3, 30),
    stat("NZBGet articles OK", "nzbget_history_article_success_count", 0, 31),
    stat("NZBGet articles failed", "nzbget_history_article_failed_count", 4, 31,
         warn_above=50,
         desc="Failed articles are the usenet equivalent of a bad sector - a "
              "few are normal, a rising share means bad providers or "
              "retention gaps."),
    stat("SABnzbd article cache", "sabnzbd_article_cache_bytes", 8, 31,
         unit="bytes"),
    stat("SABnzbd warnings", "sabnzbd_queue_warnings", 12, 31, warn_above=0),
    timeseries("Deluge torrent states", [
        ("deluge_torrent_state_count", "{{state}}"),
    ], 16, 31, w=8,
        desc="Seeding vs downloading vs stalled. A growing stalled band is "
             "the signal; total count is not."),

    row(Q4, 39),
    stat_floor("NZBGet disk free", "nzbget_disk_free_bytes", 0, 40,
               unit="bytes", crit_below=50e9, warn_below=200e9),
    stat("SABnzbd disk used", "sum(sabnzbd_disk_used_bytes)", 4, 40,
         unit="bytes"),
    stat("SABnzbd disk total", "sum(sabnzbd_disk_total_bytes)", 8, 40,
         unit="bytes"),
    # NO DELUGE FREE-SPACE PANEL, deliberately. deluge_free_space returns -1,
    # a sentinel meaning "Deluge cannot determine this", not a byte count.
    # Panelled raw it renders a confident negative size; filtered `> 0` it is
    # permanently empty. A knowingly-empty tile is still a "No data" tile, and
    # the rule for these boards has no documented-exception clause - a reader
    # cannot tell an intentional blank from a broken query. So it is omitted,
    # and the reason lives here instead of on a dead panel.
    timeseries("Downloader disk headroom", [
        ("nzbget_disk_free_bytes", "nzbget free"),
        ("sum(sabnzbd_disk_total_bytes) - sum(sabnzbd_disk_used_bytes)", "sabnzbd free"),
    ], 12, 40, w=12, unit="bytes",
        desc="Deluge is absent here on purpose - it reports -1 for free "
             "space, which is a sentinel, not a measurement."),
]

SEAM = ("Live playback and transport cannot be attributed to a content "
        "domain with current metrics (no media-type or library label on "
        "session or queue series); the per-domain view of this stage lives "
        "on the Media - Movies/TV/Music/Books boards.")

BOARDS = [
    ("Media - Streaming", "media-streaming", STREAM,
     ["media", "service"], "grafana-dashboard-media-streaming",
     "media-streaming.json",
     "Delivery to a human: Plex, Emby, Tunarr. The purpose metric here is "
     "streams and how many are transcoding - a Plex at 3% CPU with every\n"
     "# stream failing looks perfectly healthy on an infrastructure board.",
     "Delivery to a human, whatever the content: Plex, Emby, Tunarr. " + SEAM),
    ("Media - Downloaders", "media-downloaders", DL,
     ["media", "service"], "grafana-dashboard-media-downloaders",
     "media-downloaders.json",
     "Moving the bytes: SABnzbd, NZBGet, Deluge. Paused state gets its own\n"
     "# tile because a paused downloader is indistinguishable from an idle\n"
     "# one on every throughput graph.",
     "Moving the bytes, whatever the content: SABnzbd, NZBGet, Deluge. "
     + SEAM),
]

if __name__ == "__main__":
    total = 0
    for title, uid, panels, tags, cm, key, why, desc in BOARDS:
        d = dashboard(title, uid, panels, tags=tags, desc=desc)
        path = os.path.abspath(os.path.join(OUT, cm + ".yaml"))
        # Render before open(): open() truncates immediately, and a lint
        # failure inside emit_configmap must not delete the previous good
        # artifact.
        text = emit_configmap(d, cm, key, hdr(title, why))
        open(path, "w").write(text)
        n = len([p for p in panels if p["type"] != "row"])
        q = sum(len(p.get("targets") or []) for p in panels)
        total += q
        print("wrote %-46s panels=%-3d queries=%d" % (os.path.basename(path), n, q))
    print("total queries: %d" % total)
