apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:hXH1VUSVfrUOl69gkLxgpRhq2NW7ZSHJF8azyKCzRwhU7WjzGXCNOULqqsyrb+ylgaMTEUpALiUBAiG84rYksA==,iv:SaD3uQg8nghd0/XxTE3TV+DzdiY6WVd2AyIBSOwDkPM=,tag:/RAmfhkDFbZf8T4OvH0IeA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRE1WRVRpRlV4R2d0SG43
            cFVmY3ZBb0pGMjZzQUE3Q1FGRmp1R0RjajBjClZPUVBURm5JVVVDSEVNMzFGOXNP
            cTNKOGllRldTWmpGQ09jTXMrTk0veGsKLS0tIEJsZVNUV3FxRkZOampuM0RZeUVu
            RWhZTGFsUWNXVVo4N0VCeUNYY2RjdkEKKDnewqUWjmd7eCbJ053hvNNZDuVvhWMf
            Fq/h9CV/MaY48sgthjjVzJVCGqJn8sGdCWMCAUyOclOVXpAypWi6Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T17:38:02Z"
    mac: ENC[AES256_GCM,data:rV98FXxXcXayeJvsqX0xO2cXiACTigVQXyUhwCKAaY7G1S+O1dSkY8oiWA1PaGRu+aXWccVFOsUM6+ASheKU0WDtqsRt1wypyuQDuc8zcmCxuLVxp33u3ZLXoo+A5C9EkI7kElzh4GhMdy0Zvn9oBtGjlUWgJIO6tG0V2+Wk65U=,iv:QGBU8JEOIMFnBkXXIcEnk77KEzU1qC2grtWIUso+v/U=,tag:7/Nr3r9tu/tM9UwaMPIOzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
