apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pB+qzFEU8xWzZC77/owSb1JL9Ga0PynL4N/iY8B/ieZdVBPZAzylRFwEUhzEHQ3CjuVq6zRh9/7klMvkZeYWPg==,iv:JalIU9a6g2R7cwmSWESr96hSLc8SNk3ONt/mdDvqif8=,tag:kXTKqrQbFY1zDxGmyGcMEA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y1V2TzhRemhDMnZubmVo
            UllIRmpxaGhLYllUV1dvUkwvYmtpN2Rad0JNClV3S1htTkF1YUcvend4Sm9PeGFw
            VVVvK2prSy80N2xaNi9MbE11OTZlWUUKLS0tIHhHdENkTVduekpRM0k0c0p3eTlC
            M1E1bVpBd3VDSWdEdU5ESk1TZTgwcW8KHtJayhJuHmGt28dDaflHiWGrFwaWgrRL
            dai5ayHTRWR/Qx5EQBU8g5SOyo7a2uf3kuUtYNemYNAEuxDffhVG/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:20:46Z"
    mac: ENC[AES256_GCM,data:Z8Tt96FmjlujGN8hYlsFGlE4mWVkXe9mlb6wdKxbbKMtWpnrmvn+XVcEdzhQxEEtq2+HHk2Ewh2PIu2QLETLHjWfm+z+XspU3x78m+LBgVsIQNjkHkTkAyGQLLO5ury8tNpvTGZcq5w101PUr5jLArKWlATM/JKzb/lOghLEzvw=,iv:yNzSVwZKWPgQLnV7JNLWGxd0+Y4dpmbc337czfNUhMY=,tag:gB/IrhHgbRGnBRZ7LMgqwQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
