apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:iSfQViaVFzEHQ9c8scjCfphj2EKVFN+eNzHdQv8OI8H8IN+5dpEd8cuXnvxhRRmtghRtDsM8fkMTDNcqB7S+Pw==,iv:KrGT6DSAPGh7907VqWu4SSyxkiFftq6/eUgezJjcIJg=,tag:o8TiSMA18n4IjA6EHpzH9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcTFSL0VBN01lTUkzQ0k4
            UGpsV09QM1FCTjRtckdqTVhpdkprSzk4WkVvCk03N0VkMUF6emdCT1ExNnZLZ2ti
            ZlVVT1hUUElLQzNQWVp3NThyRzZpdWcKLS0tIGZ5SkFMRndwTXNIRGFRSUxWSVhP
            UjBrSi9IR1p6bTN4Tm1kNmR1bHYwU00KggQgKPRs8P8giLpyqulut/xM1+aKJadp
            JRdLWYMlHnOHdptZv/Kqee/JyjdqwLJs2fmpY00gEED0w6BaMLP7TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T22:37:26Z"
    mac: ENC[AES256_GCM,data:7hgSFlwukwmo0s9KSKleGwRTfiruGU8mDWv+RDkaAF1+Pa39HOv+urb5GkK1HG0cLBBIAQXaUGShdTn6yc98e5OA7xj3cOTvkCHTShHPFWpeD4OSFNxqIumceuuQ5iC+EvY1lJaB6NnUKQnvhqq1X4Z7wkfPxkBz8QDJqx1NxwU=,iv:qC2iZ9n/Zr0Pfcv/GSEsploX2k8RnpiOSlzRsGEFOIs=,tag:rpIvbWaYxrWSlwZTqJVJWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
