apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neo4j
  namespace: flux-system
spec:
  dependsOn:
    - name: sonarr
  interval: 10m
  path: clusters/main/kubernetes/apps/neo4j/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
