apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-auth
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:W8RMzg==,iv:ApFqsAmJ6AEtrbSCT144mK0NHk8XCK1yJ7YtY5U73Ag=,tag:Fwxk4sxfqMXMJxO2lbbvvA==,type:str]
    password: ENC[AES256_GCM,data:bG4odz8cNzm7neAHQ6HM70MD4A==,iv:QmBicruIGLhTRxsFasOD2RHJfaV2HqIp1/SiKoA6MIA=,tag:SXPItAg4eRNFd4EniG3zSg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YnY5V1l4SnhLTXFPeVIy
            SDhzOTdVbGtyT1FraXVMVURKeS91N3ZodVFzCkMwMjRXVUpMcExCbEVVZWVTWW1N
            d0J6S09BMnN3dVRzamx3WG5KM1JqemsKLS0tIFVtbThwa25GVmUwVi9ONloyNE56
            WExobXltbmM2cXRQN1JadytKTzVEd1kKrT5/epuaE6AAEsgG4aVgxJ4b160tjgXT
            bclKTwU8T/RfA+/HOO8hczvXBmnXH53Uzh1KIJhuvGQKrYkK9+fbRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T17:38:02Z"
    mac: ENC[AES256_GCM,data:q7QAu6WDxwsWOL4VhZ9oRuBy16VMxHIyFcP7cXd62FPTT7y5BdkKZq1jb7Q6yW3qqssni85suy19Z/s+C2SoCVvMs20QOAr7XBycLhwXRJTDzziJHiso9VGW4bcMofsLAkh2tO1Eejn5PHJ1yJ4cA+Hzdn42AZtPwcHnETnXmI0=,iv:jU6/iAweGaiaM7MPUmhL66PewYjc3pzUxhBno0YLe8o=,tag:3bNCfTNtZyQzmxbRmgq1dQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
