apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-auth
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Dk84HcqTTtd+f3PmAIKiSumavzvMjO29r0jKZbdzWs/PXjNDCrACY7sKROj+VoxmMhDeOEojs2CZuMxTQVziWLd09SrCZ98=,iv:vBAMqOZ5w6moZuKUD1xIwC6aAGExaAvU5zvBDM1Pa9k=,tag:dgAyEhp8SW++57q+m+kaHg==,type:comment]
    #ENC[AES256_GCM,data:YspV6/oraZhZQ1SLZ6tjveS2LS0T7DObZoJoAuPv2aJQS5f3UBnofNQBU5A9DtIlwnxwLdZ0MQ6WJOf+0zy9bCufXRIxHAj7HxOpRbDdgSg8La8wxQ==,iv:GDelq9JxCWgrh+DGyYfuuNVTCvuUSSh0CU3G7PruvrM=,tag:uMvrEGo5AZwovuVmJGfi1g==,type:comment]
    username: ENC[AES256_GCM,data:vqRIKRCBAq8d6Y/tEqwgGgtm,iv:soF1505cEbcXl/g/BGgttjIkqtldhWaNcqbi76hDXGY=,tag:h6WqW8mOhTkHv7mUxkx1qQ==,type:str]
    password: ENC[AES256_GCM,data:EIH6FE0mKbAeleXLh6Ufs6e8UaWl9tiM7QkOyQpaW9ld1VbwnctuqQ7dQU8=,iv:yEhX7gBdq8wFhnrCzhXZLl9oKVSk/HfafTsJSQnMpFA=,tag:j9gw5zbiZZ7sBfEIpGEonw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTS82ME1YZVVUNnhuTm03
            VGdKaWUwL0ZONUlBNzlFeGhiUmI2bG1ZWFU0CnZvbWIvR0IxdVdvSFVuR2dIZzND
            OEhtaDVOT2dobEVBNGVNdTFBUXRxeDAKLS0tIFdzNkdNdXJzVG9qNkNSZTllZ2Iy
            OXpYMFllWEdRSXhrMXY2cWtORjVoREkKIYoBS4r9ApYJYtOLHX7cR1uhdPXkwrBb
            06FB4laJ5Jw4RSJG9TG7nzKTn3nQDwKRhwz813TCO21sA+jrJKyJPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:kI/1Grbx95l6rn+G7mHUNl52CjNaLpNgqTDW2ZAhCF3j3LAMFXyKj8T/WsH1qPGL9Av4LaHIsVB7nSNFGDJHIIIV9Jb34ljRfkEg/E0V5t0Dk8cjGC/G0asfQoL8lT1yS+UvvCEMU3K85i7UCaWdMlO5qzqWxdFTJ3VBu8QVikw=,iv:POJhJLJ6ubdftRkLYuKpS90wV+g75rRltR/Z8h36Yd0=,tag:pzSR8PPzsUWPEdcQQW2tnA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
