apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-auth
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2Spa9uSZJByqfZpUrP+PHXMWfU9fJLzDgr3ALStbnSrJ+uf8PMYsPMd+/2LEDw23TSeO+beU+eSnQpZ1hrMu8XoiBe6F2S8=,iv:DirC7RdrQN4qKVPZeTze9UYqxEnthcpHlGpO89eoqwc=,tag:1/5H1l5TGi0a/6zITebaDg==,type:comment]
    #ENC[AES256_GCM,data:ghehuIpC1QDSK+ww9/mJo8zLAgN5s/5IU3kw8IWdtf13LK1yNtY8tIV2m9IrI8/vnDqZHSQeJdHIW91G5ute0Aa7YhAGFe7D++4HB5rYcqLS7ytKDw==,iv:Alf7A73fu36ozuZwMJl+Q5LHSztCLIaqN5KZQCQcxK8=,tag:7MYkXlJvy8Z8Efa+AjulQw==,type:comment]
    username: ENC[AES256_GCM,data:yFSENwOE0dTvk7p5uyqrDvdk,iv:jR0kmkpULcwVsyk/GzQSgifREVjdKi46Zmnjk3AOVTY=,tag:F746Xp0SPM7MhftQe7f6iA==,type:str]
    password: ENC[AES256_GCM,data:R+oJmGy302jvKwX8Tc54+J63o6/mWwXPP1QouqGQbZYI4yswJYSqAzNG/E8=,iv:w5SeybJY0WN+pBsGA8UU4Efy/o64jJxb9IinZmuiFf8=,tag:TCNU+EM9/6yzwS8mUHSx2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYXFMak4zUjJIcTdiU1pF
            Z2pqdEpRU0FaQXQ2N3B4bmVVYnByM0gyMnlrCkJkeUtJeU5DYS9qWHdiRkVxTGY0
            YldINjBSbndUL3AzdnRHQkJkcmY3TVUKLS0tIHFGbW5jMWZTNnJrSllSTUVIQ1Fm
            dURrMDhiQitFVGFlbnd2Sm9ROUthN0UKGWR2ZrH3SSRi6HfWakv9knpOlq92NLyG
            RC7FV/UlmeG/3CSLWt2R1OdZLqQRkP1AWRQU8yi3qjkNq3rMZ+OTfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-19T05:04:00Z"
    mac: ENC[AES256_GCM,data:EXRNpM1FwQDAVPmTCep7nlPQ75da1kjQU6tWPN5zxm/jW+9f5VsO4T5Y42Ro3PfgM2dDhiE9uB9pqGsnBDLIt57jVGLBsEzvfolbmx43BAiieRYS1nH6Jqb5gUrbW6xhyeNjOJ/BlHyWJKYDqqQqy0RP2QWQ2LzxxejFOt8J1oY=,iv:paBbo0aMceHgSd7B1i0zqmlsSTIl+mHmRW3V1fBJKik=,tag:9toJOTEBcBZpqqZP8FlAEw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
