---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: tools
spec:
  releaseName: paperless-ngx
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: paperless-ngx
      version: 13.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    credentials:
      s3:
        type: s3
        url: ${S3URL}
        bucket: "${S3PREFIX}-paperless"
        accessKey: ${S3ID}
        secretKey: ${S3KEY}
        encrKey: ${S3KEY}

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${PAPERLESS_IP}
        annotations:
          metallb.io/loadBalancerIPs: ${PAPERLESS_IP}
        ports:
          main:
            enabled: true
            port: 10140
            protocol: http

    ingress:
      main:
        enabled: true
        hosts:
          - host: paperless.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: false
            ingressClassName: internal
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: secure-chain
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: wethecommon-prod-cert
          homepage:
            enabled: true
            name: Paperless-ngx
            description: Document Management
            group: Lifestyle & Home
            widget:
              enabled: false

    persistence:
      data:
        enabled: true
        size: 10Gi
        mountPath: /usr/src/paperless/data
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: false
              cacheCapacity: 2Gi
            src:
              enabled: true
              cacheCapacity: 2Gi
      media:
        enabled: true
        size: 20Gi
        mountPath: /usr/src/paperless/media
        volsync:
          - name: media
            type: restic
            credentials: s3
            dest:
              enabled: false
              cacheCapacity: 2Gi
            src:
              enabled: true
              cacheCapacity: 2Gi
      consume:
        enabled: true
        size: 5Gi
        mountPath: /usr/src/paperless/consume
      export:
        enabled: true
        size: 5Gi
        mountPath: /usr/src/paperless/export

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
      pod:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch

    cnpg:
      main:
        cluster:
          storage:
            size: 5Gi
          walStorage:
            size: 2Gi

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        cpu: "2"
        memory: 2Gi
