#ENC[AES256_GCM,data:DJmUa1jqEuy+gkPbwKIt/8QnluWpFjsLQcHhDC3ccqbRaZ8dPsKBp22+8IRyPn2C7WbBAakaOQk02wrbBCn/mbZ7wQ==,iv:wInRshEYiw9Ug86j8cTfkXNCAhE8SXA2pqRXO0ZMyBs=,tag:d0VWfyqoRZrjGZaX8zMDzg==,type:comment]
#ENC[AES256_GCM,data:F/jwXReduf/LtEtqiFRp2b8vUNWIRus7I8on5n3Isb+Jy0ueQU0MKuPGq85kOUDAk6yAf/cCLMhBvKrZeVRRkqdTDMc1,iv:OBWev5hLFZVf0zUEl1a1KS2HlpTxwHKakTTzw5xDKD8=,tag:ovi6i7MpqZHx2s1PMCHf9w==,type:comment]
#ENC[AES256_GCM,data:FmXIjU4w3rwUFZKtUlkGOO4yjujexnOMf1X7q02SNaFs1cOgePCUn9Js+TYS02YYWtI29qZpxMcB5xDViGXL7w==,iv:xchJLyvIRjQHIdjx7U96dUsVV1oLoxo5E/ZKXmJjf+s=,tag:Q7L1F+0LJgP68iX7X0W1tA==,type:comment]
#
#ENC[AES256_GCM,data:UF3RQSfs7Iz352vkWvmaMZAavW82OoYXHRWjmGkdsRLIYy0fDlfKprIMRrAfAiJDLCSRrozwoReoAkKjeA==,iv:mL8eEylb2Vj83HEIqu933agJ7iXMbkHOkPp5CUAC4cI=,tag:ovnlSCPZyIi8H6cHYQ1HlQ==,type:comment]
#ENC[AES256_GCM,data:Zf+WredsadwXHuHtzbb0lqf4Udw42rbE8qPqka4HSqzuYorCISKRgmdG8xbwvnfoNihr0dIbC4kuHI9LvyzdYM1HdSA=,iv:U1KDBFzs8UhbIe5hcVZxZ4u3jMN2qh4/3na0sXSxZnM=,tag:j86ciAYRbqiKYL+2o0p4KQ==,type:comment]
#ENC[AES256_GCM,data:vfGlsQaP5EuXF8GUGT47CJIE770hL5JyysbPg7SRLkmjotKX3wt+/b7IkWf4HEuAOUxXLN6Ag2u1ghgJZ9PUt+hZ5oAIPgg=,iv:Sz5vD4OhGJr0UR6G7wZPQgMq67gylx1MLaeGZrQFjcY=,tag:kNJtFmOhSW90UTtTrVG4cQ==,type:comment]
#ENC[AES256_GCM,data:j6Vo/pZVptxUzM8+2VBgiyoRyxjVc9UYS2/X455HYhvSaO3rYPw11KUzwrC/0i9oSRhzIwDHeorVCzhQHImL4J1ZI+sZaA==,iv:uJaftAtOtvdhss8NKxQBKUXkeMxeXENeOMuzqCU5jn0=,tag:CKHiWWwOksxV5inr2z7j4Q==,type:comment]
#ENC[AES256_GCM,data:tGnzq3bRGKoUWyp7QitKPI/NOCK21YlINMwaMIeuG6mznnmxHfC3LxkPvEz5yTocDH36L5sIjdtFpNUhc7pWfs/1GZCEjfA=,iv:WmhWrRgr1RaaooXCzbtwVO2c7bGRsn051sEgeicodJ4=,tag:QbWzDwi9qIgFLInfzSQJcQ==,type:comment]
#ENC[AES256_GCM,data:23HDUavkuhM0Zk2z2p1YELV/wtZL7zvH08CH81SOxrVMSmu9pz62rYTV7Sku0B+91jv9SQoQhk60TeJ3e++2uQyfuH6RVlwB9A==,iv:0nyKtnSWvDcOo651vjcHB7FFT4fSfgwi/vXwjoh6+9Y=,tag:Nln2dxOeYYs/ncHxg/0JCw==,type:comment]
cluster:
    apiServer:
        extraArgs:
            encryption-provider-config: ENC[AES256_GCM,data:PoGxVvjS8P3E+pZfE5Vo8JuZawET9Tyq11fFL3pjcvoc2lf0aec=,iv:stWbj8vfzeGDUNc8uH7I7gC42wPsY/v9C9c34B9ttVU=,tag:uaXbYzHoSGdXUB8TPJr6MQ==,type:str]
        extraVolumes:
            - hostPath: ENC[AES256_GCM,data:JHl3L7WNfveIg6MpeHQihvWvxpvtj5qW7wCrX44x8IcaiPn/sxY=,iv:ai9P+DWsZRz211jV+zzYoyoxdB1pbTvUtv2zvvPB/gk=,tag:i8h4PzhVhLJKq3eCvnSSCw==,type:str]
              mountPath: ENC[AES256_GCM,data:1TF02SW3dYeM13stuvfvwjsi7FR0vL227Wvsgc4ZSDJoXg52rHk=,iv:YPsPr5I6gs0Jz0RKUzcZIqglqslIsMl8hiQgrgQWdPQ=,tag:Ng0hMxkgdtgA/fHKsokeLg==,type:str]
              readonly: ENC[AES256_GCM,data:XHgp+Q==,iv:IV6evEViEQTlneUv9L3MdPtWp2BS2pZlMLSuqdj2HrE=,tag:rQ6AoyBhhHrs8knZp50vOQ==,type:bool]
machine:
    files:
        - path: ENC[AES256_GCM,data:vm1UhFiU0yU80QAFESeTekF55cfG8JST3wLmaWC7mSojQ8yTZNk=,iv:yH3MY3+a3lgx7FE7vrWKOBL6FjLMHc0Bg0ysj/av4mw=,tag:5kWXT4bEJE+wOzysGyQohA==,type:str]
          permissions: ENC[AES256_GCM,data:Lemv,iv:4j6+nz7wB/WfaxvEuneeCiyLagPxgVUEjh5ntb0MBCs=,tag:MQw2f3VJ8IdiwL6PBYYHCQ==,type:int]
          op: ENC[AES256_GCM,data:qPW+FS+b,iv:DoFjRartZecTJrpABqIe7dHstyZekapcTjGJpDEdqXQ=,tag:gu8MwegASf3IxjT+Y1lRQg==,type:str]
          content: ENC[AES256_GCM,data:khS8QY2bUuQyXQrlzJlDuVY/GQbKMcWEdsprPtptx3PLszXBjlomZDiNNSqpG8Ub3sadVKHv+1dS1lmv8JxtIjL0xnm2rGPu4K/wV9Vc4YhX5X568P09fxA4/VJUlBznTh2F3v8invwlZQPhfAG5ZpiXRmA0XgOeZCIh4YAVhDxRwxQSEHn/8XOv3lMkt2oi9J16io6hbdvAg7kyaUPg6kEkHaznw0KPCIYjzYsNk0xOXeu5YpKIwyVSFDR0JSXPitvfD6EMHkPgU56E9qfADyHxj+4R4EVPY9cv8Etpg81Cfu7fwkaBXxxWfJZ0K+EPwgkgIpKLddZADVdz9sWm2FxaS4bF8JWY9mOLSjaClQ==,iv:4aaTdq8XSVOJ8OByv7PsVXuw4Yvzy7TLg+fOItnQNj8=,tag:aZh+1GCj1gcahC9wqLpWVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycTRkV0xNNmlPRWF1dW5I
            OUtHVkUxMTl3amJqRVk5dW1vZnlXVVhKaW04CndYVERRMy9TNnAyK05MbUlpdWRJ
            SUg0dExaNkNUS3l6cWY3V00zUTRLaEkKLS0tIHZGUTdtS3JBTTN6Rm1OMnRZR1Qv
            eEpjUE5NSzdQdG5jbmNkZ2wxUGFQVjAKpuO3DNDzKyB99/VZe5Ifz0W2d8e2f12p
            0vrHW6yM4nYjGrbfFKjUnE0gE8OX80mNmVlV6Ds7VFiGRE/fBHrJqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    lastmodified: "2026-06-09T22:16:03Z"
    mac: ENC[AES256_GCM,data:73qS9IdcnUuf+ag01/nGhwQd5roiWhXAHRwjRYIef712mTdZWFZq6J61ZW2MN41LGyaHu6gd9rIxI+Aq9fJEjUAbJL7deLAFoJNsnA85eJ82cZxRbnbgIqPtU8r8DocYi3qkkhGlcLkDhf2Grj19gzaJn41lzZH8YvZgrff2Upc=,iv:ggzrFFiawchhIHuTJbGbZT4LJsEwRDZWUhpJpXXqa0Q=,tag:+4QtznwezGygwi42Vx90Ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
