#ENC[AES256_GCM,data:g6neTM3JOzw7gsFkL+3YuhFtoyAMEPq5/mKhj9kfxU/i8pTV1YwUHX+CF8QAyRGitWcqzUu5tSNZ75PyN5BSsHTHqw==,iv:umClVcUSACEbSCP1KT8gBDGn0FYUslZ2tNWBYW0M0Ns=,tag:PRCmKjaxXtpvr8L7wzqN5Q==,type:comment]
#ENC[AES256_GCM,data:71uTO+tPI3C/BIJxIXwL/DiD9mqBxcIBFm7rh6HQu0U+WMscCSKMZVEzivDnj7vDy9IhouAZfQqiE03ZtZaHgI1NU6mj,iv:FYJqhxrLefU3FwSSuJ4hyY+YvVcjjkaTPzdLLDgqUAo=,tag:pSbTajKr6PbwHdmkmLhm2A==,type:comment]
#ENC[AES256_GCM,data:9EsvLiZk5xNaZPEt9lwgduLCNOkufF9wvwWCpoCUaPFQXS9QcvHGtp/HxG2n+K9Kb8kKfvqzCtwQ/GCgjS7CsQ==,iv:aXJeZYz7embgyqh/jeSC9pNie3EbOLdPwHeoMBDPlmY=,tag:/0jm8oCFnuqycwfAxQkGVw==,type:comment]
#
#ENC[AES256_GCM,data:icRueKXnZ8H589MJVqWTenS2NTSKfhz2rdjOsXgUe3dtCxBfhINvd8Q+5ufc1X9Mjg0999s+R2FreU7SoA==,iv:1y3+U8e0OPptQqaN6X3Ebn2twz9XXjlVSBnz+AYjTRg=,tag:GI1CNIjr2x7KX+1qqV2C4w==,type:comment]
#ENC[AES256_GCM,data:tRZKW2jUtBBe3s+RpeMPBTj1Rp4Bl68BuDlHNNyGOmAdWBb6aOqxD8yDJGIbxZjVKigFyklWwByuIYkFgauVgfY6RXQ=,iv:alWZjnA/6cFck8fqYL15yHmupm0cDhuJx04Wd4/ZS4Y=,tag:ZLGOyVypAz8nzULKSEdCXQ==,type:comment]
#ENC[AES256_GCM,data:c3MqmEyZj+BV4A+EHzo10ZNzkYuJFWosNRFj9x2y+BO8hvT9h5Q06eQchLE4qXV54huxB3cgpmWZ1KOmW062eo//ipgMtFI=,iv:1NPh9w1hZXRJwJBdz2esAEF/lhIElsffY97So0kyXHo=,tag:NThHoLXK4E1rm/j48anoXw==,type:comment]
#ENC[AES256_GCM,data:1Sgj++2lphBKS24sC+iUtmXC5hRAtZZFLUZX/qKxVHVZelgQrxNEjXUPTpp2Smx6W5O3ZIjpAhl45FjbW2igUwW27x9V6w==,iv:fIG7iYkQmR4w30G0dScvpiMW70Kr6ov7fEuaUoLoPIM=,tag:yqH9CDquX5nsB8yk8xup2A==,type:comment]
#ENC[AES256_GCM,data:YE5b3JNaPuR93L8T7UvfNSDxlFD2acMYegWXzt0qQQn1FrZBY5/U1GdyYo7G3roBip6xffEHPfFvTGrLhNlmUEwO90GRdiI=,iv:lPJO4CAkywScs1CgzPy7qyVGXMu5NEbiuhoz0fFLR9c=,tag:xFpCcZp+udkkY8d4MSfMdQ==,type:comment]
#ENC[AES256_GCM,data:91xc041dwfqXfQz33/2jKcPyUw/u1MBDwulkPprZ9ov3bBNRabUCZWzew/WGVDW95uf2mGtNwtId1G3E3Fp4o+cWrABlbDr6OA==,iv:f45FQdfzKHzTcXqIu+riOfZHxi2HyfUHxNPGfvBKl/Q=,tag:MBH2r/l2Y9Lvwq3pFIFESg==,type:comment]
cluster:
    apiServer:
        extraArgs:
            encryption-provider-config: ENC[AES256_GCM,data:9jlbCz1Z/FawSU4h9fHMfMEYbDGq43f54si2wJR/syRD1/EBpIk=,iv:wxcWkugbpEPGC/b3tdmXK9RGQGjv19TacMLE4PdyGKs=,tag:HLie37S7qfURfQtU/IZ9eA==,type:str]
        extraVolumes:
            - hostPath: ENC[AES256_GCM,data:D3/y16JlY78rVJlRDFrMYvksBPX42oHKPzWp/55fMeBZs7alVbw=,iv:hklwaDzx3mEJAJY9Lf2ZHGOlEKUNPcxfUgBW7m4yY4w=,tag:Pzk63oPuya6ZkH84njJOMg==,type:str]
              mountPath: ENC[AES256_GCM,data:7Fmkz5wY3WKAj9zor4CeU3h0KDC71P9ck1zOBCaB39ER/jpVHUo=,iv:dY2ufQF0S7UVjS2CKncQwTlY+LSL6xt1pV3nUkbtVuE=,tag:uPiLHU0YWBcNS1/0vsVqnQ==,type:str]
              readonly: ENC[AES256_GCM,data:CHhjJg==,iv:DueaBGOsC4XfBKRAqLyyi9kK56sptT7ULiPKakrIF08=,tag:anG45YCfWymQdrtxQlfPkA==,type:bool]
              pathType: ENC[AES256_GCM,data:v0BgbQ==,iv:Y4pU6SOUZ9DE6VnEFXRZ8SYpKEUHz/dtr7tYC4aXhIU=,tag:PKpy2qnxsJO5a3+PocGuWw==,type:str]
machine:
    files:
        - path: ENC[AES256_GCM,data:I1a5HsMUzUhUL7yv/TEceNfNg9y1kHzMsjvtDy5ne1cT+7aymCU=,iv:oM6vKxfyPJmR0asgo46jDSoJyySqs9IPL0GcGeFDB8Y=,tag:QidD6cR2piULy3WeS186XQ==,type:str]
          permissions: ENC[AES256_GCM,data:WUGc,iv:yzsUr934tngjLfVhUxwj8Wze1X6NPWaWnsuLSvSD63E=,tag:afwliV8GqG3W0RRJza4JBw==,type:int]
          op: ENC[AES256_GCM,data:k8WbyP+R,iv:8ucyAumDZEcIHxdZ1nIBOuDT6UibSmWaRhEjwMqdUlY=,tag:kyhSnWYG1PiVxFKILu+JBQ==,type:str]
          content: ENC[AES256_GCM,data:E20V+VHA6tGgxSg48Zl/KF2mETqLVmHxUE1wGXq0pmKMb5kzvgcXDzIhiPUkZfkLTI1OBWg6JiL9fujX++54OzNPnvqUk23iEoTbeTNnT2sy8G57oqJxbdra8XFlb8sZ/UkdelJ1L2un9qTVcC+1aLc0AJCCwBmI3XMPszfGUMSC9QoyUMssHzkplvvu4m2whdSXfVV/b5HZz1feyv/5XHa+qbwpcKd6s0wroH3HA1G0G0lfaV2wEfuFmZjN7CXbucyIlnJndDE9IbcC7kUomNiCK+ld4rkA3wMR0B3AYyX1hShVA9jnn3o+qbXaHMXR5ftphQBfRvDZPR3RoAvLS8kcFNOUdjwDG5PKLiwNtA==,iv:dGeUwIkqgqJUD036V9TOHh2ppnm+WOeB1aO+wrxfD0E=,tag:5+UQHmQ+Qn0VU7pn1kT8aQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0dRU1BLQzVzazI5bkJL
            UmZ0VE02QW1jTEkvWTlzdXB1QmsycDRETjJFCjl5RFdEOXBGc3hSUkU4RlpjWDRQ
            K1VTYlJsbXg5My9mb0s4eE8rMUhGOUUKLS0tIFU0SU1YUEU4RkpTQVJETktCayt6
            K3U4WW9aTERZbzZ2YlhZcEhxbGx2MkkKQjPZu8oQIUGLX5JPAHPKhRfVYsxvnZYk
            W/H6LHm+nzpR2erIk6uITEe/wvihLcRC9enyzZ7016ePK+Tc9vKBRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    lastmodified: "2026-06-09T22:12:51Z"
    mac: ENC[AES256_GCM,data:fT2Ib+GcB5/ojtlDDJWbasHg0Rr3CabPpxrAT3SOn5jKnSEJQJh1zX6s3xGJ+8mVe4GILd4xG2D6GRPcnbMy3CgpSKW5Q2CtM8VPIuU7Xe6lGiKVLhAnb1Dtc+PWfGIAnchcVQsmP1WGr7gXEt+oj1q2f8D88sRJn3F1UW0WJds=,iv:ofCl22U2Zmy8WfM/ZCH4ZR+JhfnRao9TOJHMFX4NI8o=,tag:X+o110QEAMBxy2O04NYCrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
