#ENC[AES256_GCM,data:gVQ2VB29jAOVYJZGR0j+PV5jAljPTX3TUPZDmCqwa7np+trQsaWABPXlDdALs07he9wt6wlCJkz8nd1/qaXdK7p73A==,iv:D3gg+EsmpvO2ka7QQxcyqFZTq6d5KPiVoML7dwRai50=,tag:woQAJo4d3A+/6/nuvsPzFg==,type:comment]
#ENC[AES256_GCM,data:3MQU9+mlxxrohCsLIey3Jp6xsneGSSDLM2tTJprEhtO6e//+ezWxomrEsqwJtRgqQoRpFQo9bIPlcNX0vga7x/EwLCAP,iv:K8rzuNwE32JSR3CtTjRIu+DJZSyT1v3JYlqmm6ypIfo=,tag:zvYDdEpsOLFZZUHAlnEtbg==,type:comment]
#ENC[AES256_GCM,data:2MhPxx+qm3SZvyfWZPA11m48tWkJ9HlUclAUVFfWxGCQzpFV7NrSEW7z7WtAvESdgncNlHVIX+8ShSTArNwjXQ==,iv:o3oAuOM7ObR9ruPY+jmjhPs7AAHT7n7arzj0VD9PIWY=,tag:rHmFQOZTgvVHOzexO+dl6A==,type:comment]
#
#ENC[AES256_GCM,data:Oly+fi0HG7ErVZgxbQl9+tjkPWFqS4o6N6MtWCLqqTkmkUbVCzax8twdow3ZRpZTz7F8YLEi1hiwsD+06Q==,iv:fQxFQzGO+UK5am9vjQJHESY+9FocX1UBbQU1q6mB2zE=,tag:tRNjOIqIFK+1ot8pSF0vXA==,type:comment]
#ENC[AES256_GCM,data:8Vasg4rp09vxdOLvnmtmM6vFHqWU3GEUwHbmMrDbZi2cSKrT085WkA+17SgrzbbMc/Th0jOPq84oiCrYsBdkQV+ZtPE=,iv:lKkMlN0btwxh20PQ44fFaWULcWGe+jpCgDpKwb+415Q=,tag:zs4LDQXIrR4Me4exKTOOsw==,type:comment]
#ENC[AES256_GCM,data:ZsVrgazZYoVAH4bNx29QKcVtX5ezfjZLw2IXEPWHp437jFzEPB7rLUEujXqlBN/P8UDtyt2QAeSduFxRVnDbvLv8N0dEjVs=,iv:Rm2ZAHs8TYV524GaWAaYKt+upS6AcHTW0igbik6z6zU=,tag:9FBQMNyrlNG46h6e32kB/A==,type:comment]
#ENC[AES256_GCM,data:yFjhiIO94YsOzQfXFcrWFJdLzH8bnod0WhoB+8zno2JaEOxhsyvGQA/F1gu0hcDp7I7h94x3c20RdDlASciMrCLdrwY4TA==,iv:fDbXqBkJ4qCn/gJR2abSnH51lkWNIen9sIrVMiwgPBw=,tag:HTp3pakHPEWvhape1Yb0Yg==,type:comment]
#ENC[AES256_GCM,data:1UPdFUyOaOs0Akntfqvgv8qYalVStdKklQbrAKcLxp0Y5tOn31AS5sf4ty5GVSIpmexF2v29nT7AgPnkCqC3tm/DwA2wXg0=,iv:6xE6ScXTOv3tgbRqPSpZ8J9+tij1o+D8C2WYj1q4GGs=,tag:ZiPN42QycPxMBX6mXL78rg==,type:comment]
#ENC[AES256_GCM,data:FUjWoKVnIcFFp4FNntY2MQLekBp1S6xMU7UxDVIBnXCiMBdqcsNbXRhyEBLdbvwNIGLacrHZb/jPPWnplWnP9YLVU3HiWXlKbg==,iv:zPaPligwpQGRs+2Nm8YeYJWoZzfFjflS3kMTAymQXt8=,tag:9oGjH1KfnMp5rjf2rZHigg==,type:comment]
cluster:
    apiServer:
        extraArgs:
            encryption-provider-config: ENC[AES256_GCM,data:gvKquXK2azc0NMtFhd2H94SFZtQoC7j/K0no2W5lrJ/I1/x+XbE=,iv:n9h1DstZ6kjDRc7q3L1aE2TrnYQOI11z4vB0n2CkNj0=,tag:aQVSw7IE85DHrBMApvhoqg==,type:str]
        extraVolumes:
            - hostPath: ENC[AES256_GCM,data:65G2fGGhyCY2eaX0MPpqF26+pEEb2X+62AYMkadnPnWOUq0iZ1QYkopR,iv:/3utrvI0vXHmH+TUhWbI8f1zY/JXiKmGfj+4qPcI7Rk=,tag:e+CYbWczSjkXF79Rms0r5Q==,type:str]
              mountPath: ENC[AES256_GCM,data:tytqIpYnN1GDjG/ubnq58NRImZ4C/XIv6sfMXBwLxDX6FlMt+S8=,iv:BWYJ9Z5hxndUTSNNjVjDbFVxSTTNLTFxfNSAQTTku9M=,tag:QW8ncJMFOHlA/Pg86kFIqg==,type:str]
              readonly: ENC[AES256_GCM,data:tPMm/g==,iv:6vMZlf/R/CeBqMUHlXKIxAlg/MdFkXTIpyit7+yirT0=,tag:NtZlf6zYimnEOYrL8YcBbA==,type:bool]
machine:
    files:
        - path: ENC[AES256_GCM,data:1IxPMd3JnOsrCqsN5CX0M8QnVSz5WLkYwqeqN1geCNM73BUgAE0pZfR9,iv:YR02mJCJIBbVXnEgcLU67x6Jbl48SFKELjajNEhOYYc=,tag:LOWCK4qPeLK4DgfUDmqkLQ==,type:str]
          permissions: ENC[AES256_GCM,data:oHz4,iv:J/oKy2ZJNl7LvpCoKRAg6cNDMq93quIeC/9SriyH+BA=,tag:q0gfllluGyiTETG9G3Worg==,type:int]
          op: ENC[AES256_GCM,data:H47yF9/j,iv:2kIApvN3O3N7xKZ0sA+j5BoDn1O5T5JMfjXED4MM660=,tag:QHRH4PBAO7m6ccAv27w/7A==,type:str]
          content: ENC[AES256_GCM,data:Ke74jAmX6ddl7X8wUqj9MFpfyAJaQEdwingCI9w+hwnAzC28xoS+LpJ5gay4akqYxay3oSw21pGkh81vuqWaihKzmgCiq4IFI0hzfyKUlqA2n/3Pu90cZ16sflhSHcWf8xE9KaNc0JBdQ9fckKVBUd0CwPj45CEwJZ/JJXJVUD4DMWGmc83eHF8ifCCs+WspMKPmOvGP2PtNy6oj6EITJtBrUj7uHj8oAl0wSsZyjB6bkZupExBh4UbyqE/Ig17bD48+ovUCVdfaWKqMfEKrlFui2K1SSxztV12JFJ8owZEXBFgDQgiIYCQT913U7NmHTVfrMJWOciZwpBveWrQ0EqQck0NILOjC2qxjaJBkWw==,iv:Cv4T2RdA4E8mpVzg7SUPZMlCyKLUj6GcFZCoiAvF6pE=,tag:lDtQDGqUFnCfB7LBbDyw4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVN0VzJHRmZ5aE1jR3dQ
            R2VEOThBTmhzSFVzWWNMak9WWW50MWRYUW1NCnJkNnp5aW9HTTJrODZqRnFadTVC
            aC9qcXpiZVdsbUI0WkpKYkJPM3FtUjAKLS0tIG4vQng4MFlkRUd0V0xrcGFUVUww
            MkhaWG1kWFlTUnRGdTFlM2huNVZxVVEKV7mesmt/UKUK9USFty0ndmfRqHM2uLQc
            oCB2/ndE5gGclzdxMmuGCO7M/BtPu9XIAtSSz2zu3smdX4Lx80Gj2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    lastmodified: "2026-06-10T00:20:07Z"
    mac: ENC[AES256_GCM,data:EotYfsJcC2SGGhYrKPMF8BpAbhiNpILANSXFZCASs+MrI8lYR7Af4jLR3hGsA0NlvvH+UuagnngmlJ1QsG+Q573chgW/TNu6lm72b/2sazRGJDngEoQ7Hxk+vujq9Bkwnsc1LAQeUsU0DLELsrQdyXJFbhZBQSirPQcGfM/JobA=,iv:I1B5m1iH6XOAb6tnXmxX+H7MD52bdCXKEGh+sfkiJ4c=,tag:h+lgHgST8GzLPk4X8x+5Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
