apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - middleware-bouncer.yaml
  - middleware-local-whitelist.yaml
  - middleware-secure-chain.yaml
  - tls-options.yaml
