apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: bouncer
        namespace: traefik
      - name: local-whitelist
        namespace: traefik
