apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: triparr-db
  namespace: triparr-bot
spec:
  instances: 1
  postgresql:
    parameters:
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
    pg_hba:
      - host all all 10.0.0.0/8 md5
  bootstrap:
    initdb:
      database: triparr
      owner: triparr_user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
        - CREATE EXTENSION IF NOT EXISTS "pgcrypto"
        - CREATE EXTENSION IF NOT EXISTS "pg_trgm"
  storage:
    size: 80Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-triparr/
      endpointURL: ${S3URL}
      s3Credentials:
        accessKeyId:
          name: triparr-db-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: triparr-db-s3-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  monitoring:
    enablePodMonitor: false
