---
apiVersion: v1
kind: Service
metadata:
  name: goodmem
  namespace: goodmem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: goodmem
  ports:
    - name: rest
      port: 8080
      targetPort: rest
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
