---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - triparr-bot-netpol.yaml
  - ollama-netpol.yaml
  - media-netpol.yaml
  - home-netpol.yaml
  - code-server-netpol.yaml
