apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-bridge
    namespace: notifiarr-bridge
type: Opaque
stringData:
    NOTIFIARR_API_KEY: ENC[AES256_GCM,data:dBU+xjziLRU58Fg0oEirNw==,iv:MEZ3IgYexuY1GRSGTi83MZ91m4D8zcWlKK7XZf+9Hx8=,tag:Tg1ZrPpFGCMFt2omDsq1xQ==,type:str]
    NOTIFIARR_CHANNEL_ID: ENC[AES256_GCM,data:LcoL08Sv65ziEuquvwHb9acYaYo=,iv:fBrpY3ekYt2cqF27kfPRrx+5j0O53nWHXsP/jhAwSyE=,tag:go2WtdeZk6k49CJDrd1LQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2ZZSWE5dTJDc0Z5S0g4
            c0lvb2JENlc2NG9wNUFqYlMrK3JDcEtDZ1hZCnQxUzREZk93TjVuZXJQSU45enhl
            OFMzUTg1Tm1leG9saHJiQmRtbnhNUEEKLS0tIDJPbHJnMUY2anZpeTRjcjFQdGNS
            Szc5WWRxaG5EZ2xUYUZ6N3ozUE5NWjQKr5gbcS3Mv21Rgv4v0YDRYjZxkmI3D7E2
            HfrSKodnMvhwDEVsQenpsNKYD53L1VQ5dUDz5Q5AvufuA5BmZ9SlnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-27T18:14:59Z"
    mac: ENC[AES256_GCM,data:/Y2Xzy50xtdxZTTSSDc8/ajLSr63kAYiwsqt70kkeiUhPUDn3Md7FydxQqbZUYDsdTBZKHmymipABQZL6COt5/o0XRlWW7GKpAqpUHFtPHMNK1cdv+WW3Tiujt222QXHA8VU/F32qBgPgEg/YZHmnf+nNBonpT4/j28EjSSSYyg=,iv:rL+zBdh2l9Kpyj72SZKJP+Eh0Dhmi7mMOZccHpNoTIU=,tag:fqz50lRGUiAZkCVAgE0m9g==,type:str]
    version: 3.13.1
