apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-bridge
    namespace: notifiarr-bridge
type: Opaque
stringData:
    NOTIFIARR_API_KEY: ENC[AES256_GCM,data:mtiV1Yb8kXM//KhZV9ajFw==,iv:5UHLH0XR/xpx0P/dGfqlTmOAUxvPuYZqdHlvM9/thQA=,tag:OuyOmsOi+CJl/Bm8CTajgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUmIrQ2VYWVF3blYxY1dU
            UE1mdjA1dlV2VkdkUWFTSHFBTHF2d1dzejNRCmFKRkN6amErcGJFQUZUNFJFbmFX
            cUZWQytyNnRTYWo1QnNOdE9pUnVYVmMKLS0tIG1ibVhoTk9zcUpKUU9lNE9ITXRj
            a0ZGb1RNSDA1RVowd1piNmJhc3dDYTQKZxfb9xR8QB0IYZhD7eTsZM4y6M1zb4Sb
            cBlf0ttyXHURRuF9CCsForYCdutOKhgkSNxigK3u9ZrJXmlSxToBUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-27T18:28:31Z"
    mac: ENC[AES256_GCM,data:bnQGZ9E6bAWLz8qG7QRlTDt88CNgvT9Li/1rUls/x7u/i4+lWBO1ETH+J+XuzrgiJODgiihOP3pElcjbnog7usT5awl3PUJmXKOk/jCFoeIeLIugBWpBTzClXXsG+QWZyGtFU1E2qbI5BOqhxRSjuNcPly05f6kzyJBNQWbTwrw=,iv:Mmqcis3+0MFzTVKpWi/Vuu3km99OEVyNQySMl609+as=,tag:rzkMfxEz1ngn8Zvjo679YA==,type:str]
    version: 3.13.1
