apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-bridge
    namespace: notifiarr-bridge
type: Opaque
stringData:
    NOTIFIARR_API_KEY: ENC[AES256_GCM,data:dPFIK+Y5HRYUYiZLwTh+FQ==,iv:8/3alco4HS2Sfutkt21xyKpfySp2jNMEA3Y78Pw/so8=,tag:JHkJyIt5ECkS4amRcRDNig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNVNxRFRMc3VidHNsaU5S
            TFYyTXdJMWpyeUQzalFYVFB4aGdwcHloNUVJCkNXdFhwWFVkSHJWYjFvdUNGd1lB
            RHNwUlR0blM2TG5EZGpEa1hVa1ptR1UKLS0tIFREZEVRRE95MGE0ajRBTXErYTNl
            UVZpUW1hb0hMdHlKYXMvZko5YUVIN3MKc1h7SYz0lc9E2y4U88zVhEvdOUr/ak2i
            tAlwG4xeSdCA7aAHw6cg10oOaGWWXwIE9IbE1JWMlsWdzGLYOr7+fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T03:36:00Z"
    mac: ENC[AES256_GCM,data:JpqStAXSbVFYMWtWqzcC5MUMxe8HuM/AbxhrCUb/XATJ1GrDRHiXKkXlhk3WRAqFZxHUaiKyL7S2gBEfrg4ztiwNLlWedI4yz3+sUzQBR6j58UZoyErDWJjmlIJvDz7D4LVW1xtSct4pbiVF6gshz3pkSwOY/eEcO4oN9rDO2G8=,iv:6z00VPA7HF+2xN/djeSsxXm+WcBRRZkyDOQyvAD4EY0=,tag:jgEOlC0sx/z9gNImrrX5zw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
