---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-k8s
  namespace: networking
spec:
  releaseName: pihole-k8s
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: pihole
      version: 22.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    credentials:
      s3:
        type: s3
        url: ${S3URL}
        bucket: "${S3PREFIX}-pihole-k8s"
        accessKey: ${S3ID}
        secretKey: ${S3KEY}
        encrKey: ${S3KEY}

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1"
                FTLCONF_webserver_api_password: "${PIHOLE_K8S_PASS}"
                PIHOLE_UID: "0"
                PIHOLE_GID: "0"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 9089
            targetPort: 80
            protocol: http
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${PIHOLE_K8S_IP}"
        annotations:
          metallb.io/loadBalancerIPs: "${PIHOLE_K8S_IP}"

    ingress:
      main:
        enabled: true
        hosts:
          - host: pihole-k8s.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: false
            ingressClassName: internal
          traefik:
            enabled: true
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: wethecommon-prod-cert
          homepage:
            enabled: true
            name: Pi-hole (K8s)
            group: Networking
            widget:
              enabled: false

    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: false
        capabilities:
          add:
            - NET_ADMIN
            - SETFCAP
            - SETPCAP
      pod:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        size: 1Gi
        mountPath: /etc/pihole
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: false
              cacheCapacity: 2Gi
            src:
              enabled: true
              cacheCapacity: 2Gi
      dnsmasq:
        enabled: true
        size: 256Mi
        mountPath: /etc/dnsmasq.d

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
